# Generated by Django 5.2.7 on 2025-11-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('philhealth_id', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=20)),
                ('nationality', models.CharField(default='Filipino', max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city_municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('house_no_street', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('drivers_license', models.CharField(blank=True, max_length=50, null=True)),
                ('senior_citizen_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pwd_id', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('physician', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
    ]
