# Generated by Django 5.2.7 on 2025-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "civil_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("occupation", models.CharField(max_length=100)),
                ("room", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("admission_date", models.DateField()),
                ("condition", models.CharField(max_length=100)),
                ("physician", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=10,
                    ),
                ),
                ("philhealth_id", models.CharField(max_length=20)),
            ],
        ),
    ]
