import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { AlertCircle, Printer } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

interface PaymentModalProps {
    isOpen: boolean;
    onClose: () => void;
    patientName: string;
    totalBalance: number;
    onPaymentSuccess: (paymentData: any) => void;
}

export const PaymentModal: React.FC<PaymentModalProps> = ({
    isOpen,
    onClose,
    patientName,
    totalBalance,
    onPaymentSuccess
}) => {
    const [amount, setAmount] = useState('');
    const [method, setMethod] = useState('');
    const [orNumber, setOrNumber] = useState(''); // Will be auto-generated by backend
    const [cashier, setCashier] = useState('Current User'); // Mock current user
    const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
    
    // Auto-generate display OR number (temporary, actual OR will come from backend)
    React.useEffect(() => {
        if (isOpen) {
            const today = new Date().toISOString().split('T')[0].replace(/-/g, '');
            const tempOR = `OR-${today}-XXXX`;
            setOrNumber(tempOR);
        }
    }, [isOpen]);
    const [error, setError] = useState('');
    const [showReceipt, setShowReceipt] = useState(false);
    const [lastPayment, setLastPayment] = useState<any>(null);

    const resetForm = () => {
        setAmount('');
        setMethod('');
        setOrNumber('');
        setError('');
        setShowReceipt(false);
        setLastPayment(null);
    };

    const handleProcessPayment = () => {
        const payAmount = Number(amount);

        if (!payAmount || payAmount <= 0) {
            setError('Please enter a valid amount.');
            return;
        }

        if (payAmount > totalBalance) {
            setError('Payment exceeds the current balance.');
            return;
        }

        if (!method) {
            setError('Please select a payment method.');
            return;
        }

        setError('');

        const paymentData = {
            amount: payAmount,
            method,
            orNumber,
            cashier,
            date,
            patientName,
            remainingBalance: totalBalance - payAmount
        };

        setLastPayment(paymentData);
        setShowReceipt(true);
        // Note: We don't call onPaymentSuccess immediately, we wait until they close or print? 
        // Actually, usually we process it then show receipt.
        onPaymentSuccess(paymentData);
    };

    const handlePrint = () => {
        window.print();
    };

    const handleClose = () => {
        resetForm();
        onClose();
    };

    if (showReceipt && lastPayment) {
        return (
            <Dialog open={isOpen} onOpenChange={handleClose}>
                <DialogContent className="max-w-md print:shadow-none print:border-none">
                    <DialogHeader>
                        <DialogTitle className="text-center print:hidden">Payment Successful</DialogTitle>
                    </DialogHeader>

                    <div className="p-4 border rounded-md bg-white print:border-none print:p-0" id="printable-receipt">
                        <div className="text-center mb-4 border-b pb-2">
                            <h3 className="font-bold text-lg uppercase">Official Receipt</h3>
                            <p className="text-sm text-gray-500">WAH 4 Hospital</p>
                            <p className="text-xs text-gray-400">{lastPayment.date}</p>
                        </div>

                        <div className="space-y-2 text-sm">
                            <div className="flex justify-between">
                                <span className="text-gray-600">O.R. No:</span>
                                <span className="font-bold">{lastPayment.orNumber}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-gray-600">Received From:</span>
                                <span className="font-medium">{lastPayment.patientName}</span>
                            </div>
                            <div className="flex justify-between">
                                <span className="text-gray-600">Cashier:</span>
                                <span>{lastPayment.cashier}</span>
                            </div>
                            <div className="my-2 border-t border-dashed pt-2">
                                <div className="flex justify-between font-bold text-lg">
                                    <span>Amount Paid:</span>
                                    <span>₱{lastPayment.amount.toFixed(2)}</span>
                                </div>
                                <div className="flex justify-between text-gray-500 text-xs mt-1">
                                    <span>Payment Method:</span>
                                    <span className="uppercase">{lastPayment.method}</span>
                                </div>
                            </div>
                            <div className="flex justify-between text-gray-600 border-t pt-2">
                                <span>Remaining Balance:</span>
                                <span>₱{lastPayment.remainingBalance.toFixed(2)}</span>
                            </div>
                        </div>

                        <div className="mt-8 text-center text-xs text-gray-400">
                            <p>Thank you for your payment.</p>
                            <p>This is a computer generated receipt.</p>
                        </div>
                    </div>

                    <DialogFooter className="print:hidden gap-2 sm:justify-center">
                        <Button variant="outline" onClick={handlePrint}>
                            <Printer className="w-4 h-4 mr-2" /> Print Receipt
                        </Button>
                        <Button onClick={handleClose}>Close</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        );
    }

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>Process Payment</DialogTitle>
                </DialogHeader>

                {error && (
                    <Alert variant="destructive">
                        <AlertCircle className="h-4 w-4" />
                        <AlertTitle>Error</AlertTitle>
                        <AlertDescription>{error}</AlertDescription>
                    </Alert>
                )}

                <div className="grid gap-4 py-4">
                    <div className="bg-slate-100 p-3 rounded-md mb-2">
                        <p className="text-sm text-gray-500">Total Amount Due</p>
                        <p className="text-2xl font-bold text-slate-900">₱{totalBalance.toFixed(2)}</p>
                    </div>

                    <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="amount" className="text-right">Amount</Label>
                        <Input
                            id="amount"
                            type="number"
                            placeholder="0.00"
                            className="col-span-3"
                            value={amount}
                            onChange={(e) => setAmount(e.target.value)}
                        />
                    </div>

                    <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="method" className="text-right">Method</Label>
                        <Select onValueChange={setMethod} value={method}>
                            <SelectTrigger className="col-span-3">
                                <SelectValue placeholder="Select method" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="cash">Cash</SelectItem>
                                <SelectItem value="credit-card">Credit Card</SelectItem>
                                <SelectItem value="debit-card">Debit Card</SelectItem>
                                <SelectItem value="cheque">Cheque</SelectItem>
                                <SelectItem value="insurance">Insurance</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>

                    <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="or" className="text-right">O.R. No.</Label>
                        <Input
                            id="or"
                            className="col-span-3 bg-gray-50"
                            placeholder="Auto-generated"
                            value={orNumber}
                            disabled
                        />
                    </div>

                    <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="date" className="text-right">Date</Label>
                        <Input
                            id="date"
                            type="date"
                            className="col-span-3"
                            value={date}
                            onChange={(e) => setDate(e.target.value)}
                        />
                    </div>

                    <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="cashier" className="text-right">Cashier</Label>
                        <Input
                            id="cashier"
                            className="col-span-3"
                            value={cashier}
                            onChange={(e) => setCashier(e.target.value)}
                            disabled
                        />
                    </div>
                </div>
                <DialogFooter>
                    <Button type="button" variant="ghost" onClick={onClose}>Cancel</Button>
                    <Button type="submit" onClick={handleProcessPayment}>Process Payment</Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
};
