# patients/admin.py
"""
Django Admin Interface for Patients App
Provides user-friendly backend management tools for hospital administrators

Features:
- Organized fieldsets for better UX
- Clinical data inlines for quick reference
- Advanced search and filtering
- Read-only protection for auto-generated fields
"""

from django.contrib import admin
from patients.models import Patient, Condition, AllergyIntolerance, Immunization


# ============================================================================
# INLINE ADMIN CLASSES
# ============================================================================

class ConditionInline(admin.TabularInline):
    """
    Display patient conditions inline within Patient detail view
    """
    model = Condition
    extra = 0  # Don't show empty rows by default
    fields = ['identifier', 'code', 'clinical_status', 'verification_status', 'onset_datetime', 'recorded_date']
    readonly_fields = ['identifier', 'created_at', 'updated_at']
    can_delete = False  # Prevent accidental deletion
    show_change_link = True  # Link to full condition detail
    
    def has_add_permission(self, request, obj=None):
        """Prevent adding conditions directly through inline - use API"""
        return False


class AllergyIntoleranceInline(admin.TabularInline):
    """
    Display patient allergies/intolerances inline within Patient detail view
    """
    model = AllergyIntolerance
    extra = 0
    fields = ['identifier', 'code', 'clinical_status', 'criticality', 'onset_datetime', 'recorded_date']
    readonly_fields = ['identifier', 'created_at', 'updated_at']
    can_delete = False
    show_change_link = True
    
    def has_add_permission(self, request, obj=None):
        """Prevent adding allergies directly through inline - use API"""
        return False


class ImmunizationInline(admin.TabularInline):
    """
    Display patient immunizations inline within Patient detail view
    """
    model = Immunization
    extra = 0
    fields = ['identifier', 'vaccine_code', 'vaccine_display', 'status', 'occurrence_datetime', 'performer_id']
    readonly_fields = ['identifier', 'created_at', 'updated_at']
    can_delete = False
    show_change_link = True
    
    def has_add_permission(self, request, obj=None):
        """Prevent adding immunizations directly through inline - use API"""
        return False


# ============================================================================
# PATIENT ADMIN
# ============================================================================

@admin.register(Patient)
class PatientAdmin(admin.ModelAdmin):
    """
    Admin interface for Patient management
    Provides comprehensive view with organized fieldsets and clinical inlines
    """
    
    # List view configuration
    list_display = [
        'patient_id',
        'last_name',
        'first_name',
        'gender',
        'birthdate',
        'philhealth_id',
        'civil_status',
        'mobile_number',
        'consent_flag',
        'created_at'
    ]
    
    list_filter = [
        'gender',
        'civil_status',
        'indigenous_flag',
        'consent_flag',
        'blood_type',
        'created_at',
        'updated_at'
    ]
    
    search_fields = [
        'patient_id',
        'last_name',
        'first_name',
        'middle_name',
        'philhealth_id',
        'mobile_number'
    ]
    
    readonly_fields = [
        'id',
        'patient_id',  # Auto-generated by service
        'created_at',
        'updated_at'
    ]
    
    ordering = ['-created_at']
    
    date_hierarchy = 'created_at'
    
    # Number of items per page
    list_per_page = 25
    
    # Fieldsets for organized data entry
    fieldsets = (
        ('Identity & External ID', {
            'fields': (
                'patient_id',
                ('first_name', 'middle_name'),
                ('last_name', 'suffix_name')
            ),
            'description': 'Core patient identification. patient_id is auto-generated.'
        }),
        
        ('Demographics', {
            'fields': (
                'gender',
                'birthdate',
                'civil_status',
                'nationality',
                'religion'
            )
        }),
        
        ('Health Information', {
            'fields': (
                'philhealth_id',
                'blood_type',
                'pwd_type'
            )
        }),
        
        ('Contact Information', {
            'fields': (
                'mobile_number',
                'address_line',
                ('address_city', 'address_district'),
                ('address_state', 'address_postal_code'),
                'address_country'
            )
        }),
        
        ('Emergency Contact', {
            'fields': (
                ('contact_first_name', 'contact_last_name'),
                'contact_mobile_number',
                'contact_relationship'
            ),
            'classes': ('collapse',)  # Collapsible section
        }),
        
        ('LGU Specifics (Philippine Context)', {
            'fields': (
                'indigenous_flag',
                'indigenous_group',
                'occupation',
                'education'
            ),
            'classes': ('collapse',)
        }),
        
        ('Consent & Media', {
            'fields': (
                'consent_flag',
                'image_url'
            )
        }),
        
        ('System Metadata', {
            'fields': (
                'id',
                'created_at',
                'updated_at'
            ),
            'classes': ('collapse',)
        })
    )
    
    # Include clinical data inlines
    inlines = [
        ConditionInline,
        AllergyIntoleranceInline,
        ImmunizationInline
    ]
    
    def has_delete_permission(self, request, obj=None):
        """
        Restrict deletion to superusers only
        Patient data is sensitive and should rarely be deleted
        """
        return request.user.is_superuser
    
    def get_readonly_fields(self, request, obj=None):
        """
        If editing existing patient, protect core identity fields
        """
        readonly = list(self.readonly_fields)
        
        if obj:  # Editing existing patient
            # Protect identity fields from modification
            readonly.extend(['first_name', 'last_name', 'birthdate'])
        
        return readonly


# ============================================================================
# CLINICAL ADMIN CLASSES
# ============================================================================

@admin.register(Condition)
class ConditionAdmin(admin.ModelAdmin):
    """
    Admin interface for Condition management
    """
    
    list_display = [
        'condition_id',
        'identifier',
        'code',
        'get_patient_name',
        'clinical_status',
        'verification_status',
        'onset_datetime',
        'recorded_date'
    ]
    
    list_filter = [
        'clinical_status',
        'verification_status',
        'category',
        'severity',
        'recorded_date',
        'created_at'
    ]
    
    search_fields = [
        'identifier',
        'code',
        'subject_id__patient_id',
        'subject_id__last_name',
        'subject_id__first_name'
    ]
    
    readonly_fields = [
        'condition_id',
        'identifier',
        'created_at',
        'updated_at'
    ]
    
    date_hierarchy = 'recorded_date'
    
    ordering = ['-recorded_date']
    
    fieldsets = (
        ('Identification', {
            'fields': ('condition_id', 'identifier')
        }),
        
        ('Clinical Information', {
            'fields': (
                'code',
                'clinical_status',
                'verification_status',
                'category',
                'severity',
                'body_site'
            )
        }),
        
        ('Relationships', {
            'fields': (
                'subject_id',
                'encounter_id',
                'recorder_id',
                'asserter_id'
            )
        }),
        
        ('Onset Timing', {
            'fields': (
                'onset_datetime',
                'onset_age',
                'onset_period_start',
                'onset_period_end'
            ),
            'classes': ('collapse',)
        }),
        
        ('Abatement Timing', {
            'fields': (
                'abatement_datetime',
                'abatement_age',
                'abatement_period_start',
                'abatement_period_end'
            ),
            'classes': ('collapse',)
        }),
        
        ('Additional Information', {
            'fields': (
                'recorded_date',
                'stage_summary',
                'stage_type',
                'evidence_code',
                'note'
            ),
            'classes': ('collapse',)
        }),
        
        ('System Metadata', {
            'fields': ('created_at', 'updated_at'),
            'classes': ('collapse',)
        })
    )
    
    def get_patient_name(self, obj):
        """Display patient name in list view"""
        if obj.subject_id:
            return f"{obj.subject_id.last_name}, {obj.subject_id.first_name}"
        return "-"
    get_patient_name.short_description = "Patient"
    get_patient_name.admin_order_field = 'subject_id__last_name'
    
    def has_delete_permission(self, request, obj=None):
        """Restrict deletion to superusers"""
        return request.user.is_superuser


@admin.register(AllergyIntolerance)
class AllergyIntoleranceAdmin(admin.ModelAdmin):
    """
    Admin interface for Allergy/Intolerance management
    """
    
    list_display = [
        'allergy_id',
        'identifier',
        'code',
        'get_patient_name',
        'type',
        'clinical_status',
        'criticality',
        'recorded_date'
    ]
    
    list_filter = [
        'clinical_status',
        'verification_status',
        'type',
        'category',
        'criticality',
        'recorded_date',
        'created_at'
    ]
    
    search_fields = [
        'identifier',
        'code',
        'patient_id__patient_id',
        'patient_id__last_name',
        'patient_id__first_name'
    ]
    
    readonly_fields = [
        'allergy_id',
        'identifier',
        'created_at',
        'updated_at'
    ]
    
    date_hierarchy = 'recorded_date'
    
    ordering = ['-recorded_date']
    
    fieldsets = (
        ('Identification', {
            'fields': ('allergy_id', 'identifier')
        }),
        
        ('Clinical Information', {
            'fields': (
                'code',
                'type',
                'category',
                'criticality',
                'clinical_status',
                'verification_status'
            )
        }),
        
        ('Relationships', {
            'fields': (
                'patient_id',
                'encounter_id',
                'recorder_id',
                'asserter_id'
            )
        }),
        
        ('Onset & Occurrence', {
            'fields': (
                'onset_datetime',
                'onset_age',
                'onset_period_start',
                'onset_period_end',
                'last_occurrence'
            ),
            'classes': ('collapse',)
        }),
        
        ('Reaction Details', {
            'fields': (
                'reaction_description',
                'reaction_onset',
                'reaction_severity',
                'reaction_exposure_route',
                'reaction_manifestation',
                'reaction_substance',
                'reaction_note'
            ),
            'classes': ('collapse',)
        }),
        
        ('Additional Information', {
            'fields': (
                'recorded_date',
                'note'
            ),
            'classes': ('collapse',)
        }),
        
        ('System Metadata', {
            'fields': ('created_at', 'updated_at'),
            'classes': ('collapse',)
        })
    )
    
    def get_patient_name(self, obj):
        """Display patient name in list view"""
        if obj.patient_id:
            return f"{obj.patient_id.last_name}, {obj.patient_id.first_name}"
        return "-"
    get_patient_name.short_description = "Patient"
    get_patient_name.admin_order_field = 'patient_id__last_name'
    
    def has_delete_permission(self, request, obj=None):
        """Restrict deletion to superusers"""
        return request.user.is_superuser


@admin.register(Immunization)
class ImmunizationAdmin(admin.ModelAdmin):
    """
    Admin interface for Immunization management
    """
    
    list_display = [
        'immunization_id',
        'identifier',
        'vaccine_display',
        'get_patient_name',
        'status',
        'occurrence_datetime',
        'performer_id',
        'lot_number'
    ]
    
    list_filter = [
        'status',
        'primary_source',
        'is_subpotent',
        'occurrence_datetime',
        'recorded_datetime',
        'created_at'
    ]
    
    search_fields = [
        'identifier',
        'vaccine_code',
        'vaccine_display',
        'lot_number',
        'patient_id__patient_id',
        'patient_id__last_name',
        'patient_id__first_name'
    ]
    
    readonly_fields = [
        'immunization_id',
        'identifier',
        'created_at',
        'updated_at'
    ]
    
    date_hierarchy = 'occurrence_datetime'
    
    ordering = ['-occurrence_datetime']
    
    fieldsets = (
        ('Identification', {
            'fields': ('immunization_id', 'identifier')
        }),
        
        ('Vaccine Information', {
            'fields': (
                'vaccine_code',
                'vaccine_display',
                'status',
                'status_reason_code',
                'status_reason_display'
            )
        }),
        
        ('Relationships', {
            'fields': (
                'patient_id',
                'encounter_id',
                'performer_id',
                'actor_id',
                'location_id',
                'manufacturer_id'
            )
        }),
        
        ('Administration Details', {
            'fields': (
                'occurrence_datetime',
                'occurrence_string',
                'recorded_datetime',
                'primary_source',
                'report_origin_code',
                'report_origin_display'
            )
        }),
        
        ('Dose Information', {
            'fields': (
                'site_code',
                'site_display',
                'route_code',
                'route_display',
                'dose_quantity_value',
                'dose_quantity_unit'
            ),
            'classes': ('collapse',)
        }),
        
        ('Lot & Safety', {
            'fields': (
                'lot_number',
                'expiration_date',
                'is_subpotent',
                'subpotent_reason_code',
                'subpotent_reason_display'
            ),
            'classes': ('collapse',)
        }),
        
        ('Performer Details', {
            'fields': (
                'performer_function_code',
                'performer_function_display'
            ),
            'classes': ('collapse',)
        }),
        
        ('Reason & Education', {
            'fields': (
                'reason_code',
                'reason_display',
                'education_document_type',
                'education_reference',
                'education_publication_date',
                'education_presentation_date',
                'program_eligibility_code'
            ),
            'classes': ('collapse',)
        }),
        
        ('Additional Information', {
            'fields': ('note',),
            'classes': ('collapse',)
        }),
        
        ('System Metadata', {
            'fields': ('created_at', 'updated_at'),
            'classes': ('collapse',)
        })
    )
    
    def get_patient_name(self, obj):
        """Display patient name in list view"""
        if obj.patient_id:
            return f"{obj.patient_id.last_name}, {obj.patient_id.first_name}"
        return "-"
    get_patient_name.short_description = "Patient"
    get_patient_name.admin_order_field = 'patient_id__last_name'
    
    def has_delete_permission(self, request, obj=None):
        """Restrict deletion to superusers"""
        return request.user.is_superuser