# patients/serializers.py
"""
Serializer Layer for Patients App
Enforces strict data validation and translation between JSON <-> Python objects
NO BUSINESS LOGIC - All business logic resides in services.py

Architecture:
- Input Serializers: Optimized for writes (POST/PUT/PATCH)
- Output Serializers: Optimized for reads (GET)
- Validation-Only: No .save(), .create(), or .update() overrides
"""

from rest_framework import serializers
from decimal import Decimal, InvalidOperation
import re

from patients.models import Patient, Condition, AllergyIntolerance, Immunization
from accounts.models import Organization, Practitioner, Location


# ============================================================================
# PATIENT SERIALIZERS
# ============================================================================

class PatientRegistrationSerializer(serializers.ModelSerializer):
    """
    Input Serializer for Patient Registration
    Validates data before passing to PatientService.register_patient
    
    Usage: POST /api/patients/
    """
    
    # Explicit validation for consent_flag
    consent_flag = serializers.BooleanField(required=True)
    
    # Optional relationships - accept IDs for input
    managing_organization = serializers.PrimaryKeyRelatedField(
        queryset=Organization.objects.all(),
        required=False,
        allow_null=True
    )
    general_practitioner = serializers.PrimaryKeyRelatedField(
        queryset=Practitioner.objects.all(),
        required=False,
        allow_null=True
    )
    
    class Meta:
        model = Patient
        fields = [
            # Core identifiers (patient_id auto-generated by service)
            'first_name', 'last_name', 'middle_name', 'suffix_name',
            
            # Demographics
            'gender', 'birthdate', 'civil_status', 'nationality', 'religion',
            
            # Health identifiers
            'philhealth_id', 'blood_type', 'pwd_type',
            
            # Occupation and Education
            'occupation', 'education',
            
            # Contact information
            'mobile_number',
            
            # Address fields
            'address_line', 'address_city', 'address_district',
            'address_state', 'address_postal_code', 'address_country',
            
            # Emergency contact
            'contact_first_name', 'contact_last_name',
            'contact_mobile_number', 'contact_relationship',
            
            # Indigenous and PWD flags
            'indigenous_flag', 'indigenous_group',
            
            # Consent and media
            'consent_flag', 'image_url',
            
            # Relationships
            'managing_organization', 'general_practitioner',
        ]
        read_only_fields = ['id', 'patient_id']  # Auto-generated by service
    
    def validate_consent_flag(self, value):
        """
        Enforce consent requirement
        """
        if value is not True:
            raise serializers.ValidationError(
                "Patient consent is required for registration."
            )
        return value
    
    def validate_philhealth_id(self, value):
        """
        Validate PhilHealth ID format: XX-XXXXXXXXX-X
        Example: 12-345678901-2
        """
        if value:
            pattern = r'^\d{2}-\d{9}-\d{1}$'
            if not re.match(pattern, value):
                raise serializers.ValidationError(
                    "Invalid PhilHealth ID format. Expected: XX-XXXXXXXXX-X (e.g., 12-345678901-2)"
                )
        return value
    
    def validate_birthdate(self, value):
        """
        Ensure birthdate is not in the future
        """
        from datetime import date
        if value and value > date.today():
            raise serializers.ValidationError(
                "Birthdate cannot be in the future."
            )
        return value


class PatientUpdateSerializer(serializers.ModelSerializer):
    """
    Input Serializer for Patient Updates
    Used for PatientService.update_patient_demographics
    
    Usage: PATCH /api/patients/{id}/
    """
    
    # Optional relationships
    managing_organization = serializers.PrimaryKeyRelatedField(
        queryset=Organization.objects.all(),
        required=False,
        allow_null=True
    )
    general_practitioner = serializers.PrimaryKeyRelatedField(
        queryset=Practitioner.objects.all(),
        required=False,
        allow_null=True
    )
    
    class Meta:
        model = Patient
        fields = [
            # Updatable demographics
            'middle_name', 'suffix_name', 'civil_status', 'nationality', 'religion',
            
            # Updatable health info
            'blood_type', 'pwd_type',
            
            # Updatable occupation/education
            'occupation', 'education',
            
            # Updatable contact
            'mobile_number',
            
            # Updatable address
            'address_line', 'address_city', 'address_district',
            'address_state', 'address_postal_code', 'address_country',
            
            # Updatable emergency contact
            'contact_first_name', 'contact_last_name',
            'contact_mobile_number', 'contact_relationship',
            
            # Updatable flags
            'indigenous_flag', 'indigenous_group',
            'image_url',
            
            # Relationships
            'managing_organization', 'general_practitioner',
        ]
        # Protected fields that CANNOT be updated
        read_only_fields = ['id', 'patient_id', 'birthdate', 'first_name', 'last_name']
    
    def validate_philhealth_id(self, value):
        """
        Validate PhilHealth ID format if being updated
        """
        if value:
            pattern = r'^\d{2}-\d{9}-\d{1}$'
            if not re.match(pattern, value):
                raise serializers.ValidationError(
                    "Invalid PhilHealth ID format. Expected: XX-XXXXXXXXX-X"
                )
        return value


class PatientDetailSerializer(serializers.ModelSerializer):
    """
    Output Serializer for Patient Details
    Provides full read representation with nested relationships
    
    Usage: GET /api/patients/{id}/
    """
    
    # Nested representation for relationships (read-only)
    managing_organization = serializers.StringRelatedField()
    general_practitioner = serializers.StringRelatedField()
    
    # Display formatted full name
    full_name = serializers.SerializerMethodField()
    age = serializers.SerializerMethodField()
    
    class Meta:
        model = Patient
        fields = '__all__'
    
    def get_full_name(self, obj):
        """
        Return formatted full name
        """
        parts = [obj.first_name, obj.middle_name, obj.last_name, obj.suffix_name]
        return ' '.join(filter(None, parts))
    
    def get_age(self, obj):
        """
        Calculate age from birthdate
        """
        if obj.birthdate:
            from datetime import date
            today = date.today()
            age = today.year - obj.birthdate.year
            # Adjust if birthday hasn't occurred this year
            if today.month < obj.birthdate.month or (
                today.month == obj.birthdate.month and today.day < obj.birthdate.day
            ):
                age -= 1
            return age
        return None


class PatientSummarySerializer(serializers.ModelSerializer):
    """
    Lightweight Serializer for Patient Lists
    Optimized for search results and pagination
    
    Usage: GET /api/patients/ (list view)
    """
    
    full_name = serializers.SerializerMethodField()
    age = serializers.SerializerMethodField()
    
    class Meta:
        model = Patient
        fields = [
            'id', 'patient_id', 'full_name', 'gender',
            'birthdate', 'age', 'philhealth_id', 'mobile_number',
            'civil_status', 'created_at'
        ]
    
    def get_full_name(self, obj):
        """Return formatted full name"""
        parts = [obj.first_name, obj.middle_name, obj.last_name, obj.suffix_name]
        return ' '.join(filter(None, parts))
    
    def get_age(self, obj):
        """Calculate age from birthdate"""
        if obj.birthdate:
            from datetime import date
            today = date.today()
            age = today.year - obj.birthdate.year
            if today.month < obj.birthdate.month or (
                today.month == obj.birthdate.month and today.day < obj.birthdate.day
            ):
                age -= 1
            return age
        return None


# ============================================================================
# CLINICAL SERIALIZERS
# ============================================================================

class ConditionInputSerializer(serializers.ModelSerializer):
    """
    Input Serializer for Recording Conditions
    Validates data before passing to ClinicalService.record_condition
    
    Usage: POST /api/conditions/
    """
    
    # Accept IDs for relationships
    subject_id = serializers.PrimaryKeyRelatedField(
        queryset=Patient.objects.all(),
        required=True
    )
    encounter_id = serializers.PrimaryKeyRelatedField(
        queryset='admission.Encounter',
        required=True
    )
    recorder_id = serializers.PrimaryKeyRelatedField(
        queryset=Practitioner.objects.all(),
        required=False,
        allow_null=True
    )
    asserter_id = serializers.PrimaryKeyRelatedField(
        queryset=Practitioner.objects.all(),
        required=False,
        allow_null=True
    )
    
    class Meta:
        model = Condition
        fields = [
            'identifier', 'clinical_status', 'verification_status',
            'category', 'severity', 'code', 'subject_id', 'encounter_id',
            'body_site', 'onset_datetime', 'onset_age', 'onset_period_start',
            'onset_period_end', 'abatement_datetime', 'abatement_age',
            'abatement_period_start', 'abatement_period_end', 'recorded_date',
            'recorder_id', 'asserter_id', 'stage_summary', 'stage_type',
            'stage_assessment_id', 'evidence_code', 'evidence_detail_id', 'note'
        ]
        read_only_fields = ['condition_id']  # Auto-generated
    
    def validate_code(self, value):
        """Ensure condition code is provided"""
        if not value or not value.strip():
            raise serializers.ValidationError("Condition code is required.")
        return value


class ConditionOutputSerializer(serializers.ModelSerializer):
    """
    Output Serializer for Condition Details
    Provides nested relationships for read operations
    
    Usage: GET /api/conditions/{id}/
    """
    
    # Nested representations
    subject = PatientSummarySerializer(source='subject_id', read_only=True)
    recorder_name = serializers.StringRelatedField(source='recorder_id')
    asserter_name = serializers.StringRelatedField(source='asserter_id')
    encounter = serializers.StringRelatedField(source='encounter_id')
    
    class Meta:
        model = Condition
        fields = '__all__'


class AllergyIntoleranceInputSerializer(serializers.ModelSerializer):
    """
    Input Serializer for Recording Allergies/Intolerances
    Validates data before passing to ClinicalService.record_allergy
    
    Usage: POST /api/allergies/
    """
    
    # Accept IDs for relationships
    patient_id = serializers.PrimaryKeyRelatedField(
        queryset=Patient.objects.all(),
        required=True
    )
    encounter_id = serializers.PrimaryKeyRelatedField(
        queryset='admission.Encounter',
        required=True
    )
    recorder_id = serializers.PrimaryKeyRelatedField(
        queryset=Practitioner.objects.all(),
        required=False,
        allow_null=True
    )
    asserter_id = serializers.PrimaryKeyRelatedField(
        queryset=Practitioner.objects.all(),
        required=False,
        allow_null=True
    )
    
    class Meta:
        model = AllergyIntolerance
        fields = [
            'identifier', 'clinical_status', 'verification_status',
            'type', 'category', 'criticality', 'code', 'patient_id',
            'encounter_id', 'onset_datetime', 'onset_age', 'onset_period_start',
            'onset_period_end', 'onset_range_low', 'onset_range_high',
            'recorded_date', 'recorder_id', 'asserter_id', 'last_occurrence',
            'reaction_description', 'reaction_onset', 'reaction_severity',
            'reaction_exposure_route', 'reaction_note', 'reaction_manifestation',
            'reaction_substance', 'note'
        ]
        read_only_fields = ['allergy_id']  # Auto-generated
    
    def validate_code(self, value):
        """Ensure allergy code is provided"""
        if not value or not value.strip():
            raise serializers.ValidationError("Allergy/Intolerance code is required.")
        return value


class AllergyIntoleranceOutputSerializer(serializers.ModelSerializer):
    """
    Output Serializer for Allergy/Intolerance Details
    
    Usage: GET /api/allergies/{id}/
    """
    
    # Nested representations
    patient = PatientSummarySerializer(source='patient_id', read_only=True)
    recorder_name = serializers.StringRelatedField(source='recorder_id')
    asserter_name = serializers.StringRelatedField(source='asserter_id')
    encounter = serializers.StringRelatedField(source='encounter_id')
    
    class Meta:
        model = AllergyIntolerance
        fields = '__all__'


class ImmunizationInputSerializer(serializers.ModelSerializer):
    """
    Input Serializer for Recording Immunizations
    Validates data before passing to ClinicalService.record_immunization
    
    Usage: POST /api/immunizations/
    """
    
    # Accept IDs for relationships
    patient_id = serializers.PrimaryKeyRelatedField(
        queryset=Patient.objects.all(),
        required=True
    )
    encounter_id = serializers.PrimaryKeyRelatedField(
        queryset='admission.Encounter',
        required=True
    )
    performer_id = serializers.PrimaryKeyRelatedField(
        queryset=Practitioner.objects.all(),
        required=False,
        allow_null=True
    )
    actor_id = serializers.PrimaryKeyRelatedField(
        queryset=Practitioner.objects.all(),
        required=False,
        allow_null=True
    )
    location_id = serializers.PrimaryKeyRelatedField(
        queryset=Location.objects.all(),
        required=False,
        allow_null=True
    )
    manufacturer_id = serializers.PrimaryKeyRelatedField(
        queryset=Organization.objects.all(),
        required=False,
        allow_null=True
    )
    
    # Explicit Decimal field handling for dose quantities
    dose_quantity_value = serializers.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        allow_null=True
    )
    dose_quantity_unit = serializers.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        allow_null=True
    )
    
    class Meta:
        model = Immunization
        fields = [
            'identifier', 'status', 'status_reason_code', 'status_reason_display',
            'vaccine_code', 'vaccine_display', 'patient_id', 'encounter_id',
            'occurrence_datetime', 'occurrence_string', 'recorded_datetime',
            'primary_source', 'report_origin_code', 'report_origin_display',
            'location_id', 'manufacturer_id', 'lot_number', 'expiration_date',
            'site_code', 'site_display', 'route_code', 'route_display',
            'dose_quantity_value', 'dose_quantity_unit', 'performer_id',
            'performer_function_code', 'performer_function_display', 'actor_id',
            'note', 'reason_code', 'reason_display', 'reason_reference_id',
            'is_subpotent', 'subpotent_reason_code', 'subpotent_reason_display',
            'education_document_type', 'education_reference',
            'education_publication_date', 'education_presentation_date',
            'program_eligibility_code'
        ]
        read_only_fields = ['immunization_id']  # Auto-generated
    
    def validate_status(self, value):
        """Ensure status is provided"""
        if not value or not value.strip():
            raise serializers.ValidationError("Immunization status is required.")
        return value
    
    def validate_dose_quantity_value(self, value):
        """Validate dose quantity is positive"""
        if value is not None and value < 0:
            raise serializers.ValidationError("Dose quantity must be positive.")
        return value
    
    def validate_expiration_date(self, value):
        """Warn if vaccine is expired"""
        if value:
            from datetime import date
            if value < date.today():
                raise serializers.ValidationError(
                    "Vaccine lot has expired. Cannot administer expired vaccine."
                )
        return value


class ImmunizationOutputSerializer(serializers.ModelSerializer):
    """
    Output Serializer for Immunization Details
    
    Usage: GET /api/immunizations/{id}/
    """
    
    # Nested representations
    patient = PatientSummarySerializer(source='patient_id', read_only=True)
    performer_name = serializers.StringRelatedField(source='performer_id')
    actor_name = serializers.StringRelatedField(source='actor_id')
    location_name = serializers.StringRelatedField(source='location_id')
    manufacturer_name = serializers.StringRelatedField(source='manufacturer_id')
    encounter = serializers.StringRelatedField(source='encounter_id')
    
    class Meta:
        model = Immunization
        fields = '__all__'


# ============================================================================
# SUMMARY SERIALIZERS
# ============================================================================

class PatientClinicalSummarySerializer(serializers.Serializer):
    """
    Utility Serializer for Patient Clinical Summary
    Returns aggregated clinical data counts
    
    Usage: GET /api/patients/{id}/clinical-summary/
    """
    
    patient_id = serializers.CharField()
    patient_name = serializers.CharField()
    active_conditions = serializers.IntegerField()
    total_conditions = serializers.IntegerField()
    active_allergies = serializers.IntegerField()
    total_allergies = serializers.IntegerField()
    total_immunizations = serializers.IntegerField()
