# Generated by Django 5.2.7 on 2025-11-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('admission_date', models.DateTimeField()),
                ('attending_physician', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('bed', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Discharged', 'Discharged'), ('Transferred', 'Transferred')], default='Active', max_length=20)),
                ('encounter_type', models.CharField(default='Inpatient', max_length=50)),
                ('admitting_diagnosis', models.CharField(max_length=255)),
                ('reason_for_admission', models.TextField()),
                ('admission_category', models.CharField(choices=[('Emergency', 'Emergency'), ('Regular', 'Regular')], max_length=20)),
                ('mode_of_arrival', models.CharField(choices=[('Walk-in', 'Walk-in'), ('Ambulance', 'Ambulance'), ('Referral', 'Referral')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
            ],
        ),
    ]
