# Generated by Django 6.0.1 on 2026-01-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("active", models.BooleanField(blank=True, null=True)),
                ("name_use", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name_suffix", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("deceased_boolean", models.BooleanField(blank=True, null=True)),
                ("deceased_datetime", models.DateTimeField(blank=True, null=True)),
                ("address_use", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_postal_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("telecom", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("multiple_birth_boolean", models.BooleanField(blank=True, null=True)),
                ("multiple_birth_integer", models.IntegerField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "contact_relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_telecom",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_gender",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("contact_organization_id", models.IntegerField(blank=True, null=True)),
                ("general_practitioner_id", models.IntegerField(blank=True, null=True)),
                (
                    "managing_organization_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("link_other_patient_id", models.IntegerField(blank=True, null=True)),
                ("link_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "patient",
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("condition_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "clinical_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "verification_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("severity", models.CharField(blank=True, max_length=100, null=True)),
                ("code_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "code_display",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("onset_datetime", models.DateTimeField(blank=True, null=True)),
                ("onset_age", models.CharField(blank=True, max_length=50, null=True)),
                ("onset_period_start", models.DateTimeField(blank=True, null=True)),
                ("onset_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "onset_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "onset_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("abatement_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "abatement_age",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("abatement_period_start", models.DateTimeField(blank=True, null=True)),
                ("abatement_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "abatement_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "abatement_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recorded_date", models.DateTimeField(blank=True, null=True)),
                (
                    "stage_summary",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stage_assessment_id", models.IntegerField(blank=True, null=True)),
                ("stage_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "evidence_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("evidence_detail_id", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "asserter",
                    models.ForeignKey(
                        blank=True,
                        db_column="asserter_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asserted_conditions",
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_column="encounter_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admission.encounter",
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        blank=True,
                        db_column="recorder_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "condition",
            },
        ),
    ]
