# Generated by Django 6.0 on 2025-12-21 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "patient_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("philhealth_id", models.CharField(blank=True, max_length=20)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50)),
                ("suffix", models.CharField(blank=True, max_length=10)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("civil_status", models.CharField(blank=True, max_length=20)),
                ("nationality", models.CharField(blank=True, max_length=50)),
                ("mobile_number", models.CharField(blank=True, max_length=15)),
                ("telephone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("province", models.CharField(blank=True, max_length=50)),
                ("city_municipality", models.CharField(blank=True, max_length=50)),
                ("barangay", models.CharField(blank=True, max_length=50)),
                ("house_no_street", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("occupation", models.CharField(blank=True, max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
