# Generated by Django 6.0.2 on 2026-02-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allergyintolerance",
            name="encounter_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="condition",
            name="encounter_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
