# Generated by Django 6.0.1 on 2026-01-20 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllergyIntolerance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allergy_id",
                    models.AutoField(
                        db_column="ALG_allergy_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "clinical_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("recurrence", "Recurrence"),
                            ("relapse", "Relapse"),
                            ("inactive", "Inactive"),
                            ("remission", "Remission"),
                            ("resolved", "Resolved"),
                        ],
                        db_column="ALG_clinical_status",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unconfirmed", "Unconfirmed"),
                            ("provisional", "Provisional"),
                            ("differential", "Differential"),
                            ("confirmed", "Confirmed"),
                            ("refuted", "Refuted"),
                            ("entered-in-error", "Entered in Error"),
                        ],
                        db_column="ALG_verification_status",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("allergy", "Allergy"),
                            ("intolerance", "Intolerance"),
                        ],
                        db_column="ALG_type",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("medication", "Medication"),
                            ("environment", "Environment"),
                            ("biologic", "Biologic"),
                            ("other", "Other"),
                        ],
                        db_column="ALG_category",
                        max_length=15,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("high", "High"),
                            ("unable-to-assess", "Unable to Assess"),
                        ],
                        db_column="ALG_criticality",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(db_column="ALG_code", max_length=100)),
                (
                    "code_system",
                    models.CharField(
                        blank=True,
                        db_column="ALG_code_system",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "code_display",
                    models.CharField(
                        blank=True,
                        db_column="ALG_code_display",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "onset_datetime",
                    models.DateTimeField(
                        blank=True, db_column="ALG_onset_datetime", null=True
                    ),
                ),
                ("recorded_date", models.DateTimeField(db_column="ALG_recorded_date")),
                (
                    "last_occurrence",
                    models.DateTimeField(
                        blank=True, db_column="ALG_last_occurrence", null=True
                    ),
                ),
                (
                    "reaction_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        db_column="ALG_reaction_severity",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "reaction_manifestation",
                    models.CharField(
                        blank=True,
                        db_column="ALG_reaction_manifestation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "reaction_description",
                    models.TextField(
                        blank=True, db_column="ALG_reaction_description", null=True
                    ),
                ),
                ("note", models.TextField(blank=True, db_column="ALG_note", null=True)),
            ],
            options={
                "verbose_name": "Allergy/Intolerance",
                "verbose_name_plural": "Allergies/Intolerances",
                "db_table": "ALLERGY_INTOLERANCE",
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition_id",
                    models.AutoField(
                        db_column="COND_condition_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "clinical_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("recurrence", "Recurrence"),
                            ("relapse", "Relapse"),
                            ("inactive", "Inactive"),
                            ("remission", "Remission"),
                            ("resolved", "Resolved"),
                        ],
                        db_column="COND_clinical_status",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unconfirmed", "Unconfirmed"),
                            ("provisional", "Provisional"),
                            ("differential", "Differential"),
                            ("confirmed", "Confirmed"),
                            ("refuted", "Refuted"),
                            ("entered-in-error", "Entered in Error"),
                        ],
                        db_column="COND_verification_status",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("problem-list-item", "Problem List Item"),
                            ("encounter-diagnosis", "Encounter Diagnosis"),
                        ],
                        db_column="COND_category",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        db_column="COND_severity",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "code_icd10",
                    models.CharField(
                        blank=True,
                        db_column="COND_code_icd10",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "code_icd11",
                    models.CharField(
                        blank=True,
                        db_column="COND_code_icd11",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("diagnosis_text", models.TextField(db_column="COND_diagnosis_text")),
                (
                    "body_site",
                    models.CharField(
                        blank=True,
                        db_column="COND_body_site",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "onset_date",
                    models.DateField(
                        blank=True, db_column="COND_onset_date", null=True
                    ),
                ),
                (
                    "abatement_date",
                    models.DateField(
                        blank=True, db_column="COND_abatement_date", null=True
                    ),
                ),
                ("recorded_date", models.DateTimeField(db_column="COND_recorded_date")),
                (
                    "note",
                    models.TextField(blank=True, db_column="COND_note", null=True),
                ),
            ],
            options={
                "verbose_name": "Condition",
                "verbose_name_plural": "Conditions",
                "db_table": "CONDITION",
            },
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"verbose_name": "Patient", "verbose_name_plural": "Patients"},
        ),
        migrations.RemoveField(
            model_name="patient",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="house_no_street",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="id",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="mobile_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="national_id",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="philhealth_id",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="telephone",
        ),
        migrations.AddField(
            model_name="patient",
            name="birthdate",
            field=models.DateField(db_column="PAT_birthdate", default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="contact_number",
            field=models.CharField(
                blank=True, db_column="PAT_contact_number", max_length=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="country",
            field=models.CharField(
                blank=True, db_column="PAT_country", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="created_by",
            field=models.ForeignKey(
                db_column="PAT_created_by",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_patients",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="deceased",
            field=models.BooleanField(db_column="PAT_deceased", default=False),
        ),
        migrations.AddField(
            model_name="patient",
            name="deceased_datetime",
            field=models.DateTimeField(
                blank=True, db_column="PAT_deceased_datetime", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="extension_citizenship",
            field=models.CharField(
                blank=True,
                db_column="PAT_extension_citizenship",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="extension_disability",
            field=models.TextField(
                blank=True, db_column="PAT_extension_disability", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="extension_educational_attainment",
            field=models.CharField(
                blank=True,
                db_column="PAT_extension_educational_attainment",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="extension_ethnicity",
            field=models.CharField(
                blank=True,
                db_column="PAT_extension_ethnicity",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="extension_indigenous_group",
            field=models.CharField(
                blank=True,
                db_column="PAT_extension_indigenous_group",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="extension_occupation",
            field=models.CharField(
                blank=True,
                db_column="PAT_extension_occupation",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="extension_religion",
            field=models.CharField(
                blank=True, db_column="PAT_extension_religion", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                db_column="PAT_gender",
                default="unknown",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="identifier_national_id",
            field=models.CharField(
                blank=True,
                db_column="PAT_identifier_national_id",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="identifier_pdd",
            field=models.CharField(
                blank=True,
                db_column="PAT_identifier_pdd",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="identifier_philhealth",
            field=models.CharField(
                blank=True,
                db_column="PAT_identifier_philhealth",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="identifier_philsys",
            field=models.CharField(
                blank=True,
                db_column="PAT_identifier_philsys",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="postal_code",
            field=models.CharField(
                blank=True, db_column="PAT_postal_code", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="street_address",
            field=models.CharField(
                blank=True, db_column="PAT_street_address", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="barangay",
            field=models.CharField(
                blank=True, db_column="PAT_barangay", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="city_municipality",
            field=models.CharField(
                blank=True, db_column="PAT_city_municipality", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("separated", "Separated"),
                    ("unknown", "Unknown"),
                ],
                db_column="PAT_civil_status",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                blank=True,
                db_column="PAT_email",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(db_column="PAT_first_name", max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(db_column="PAT_last_name", max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="middle_name",
            field=models.CharField(
                blank=True, db_column="PAT_middle_name", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_id",
            field=models.AutoField(
                db_column="PAT_patient_id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="province",
            field=models.CharField(
                blank=True, db_column="PAT_province", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="region",
            field=models.CharField(
                blank=True, db_column="PAT_region", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unknown", "Unknown"),
                ],
                db_column="PAT_sex",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                db_column="PAT_status",
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="suffix",
            field=models.CharField(
                blank=True, db_column="PAT_suffix", max_length=10, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["last_name", "first_name"], name="PATIENT_PAT_las_8dde9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["identifier_philhealth"], name="PATIENT_PAT_ide_c6836a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["contact_number"], name="PATIENT_PAT_con_fdf5fe_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="patient",
            table="PATIENT",
        ),
        migrations.AddField(
            model_name="allergyintolerance",
            name="asserter",
            field=models.ForeignKey(
                blank=True,
                db_column="ALG_asserter_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asserted_allergies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="allergyintolerance",
            name="patient",
            field=models.ForeignKey(
                db_column="ALG_patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allergies",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="allergyintolerance",
            name="recorder",
            field=models.ForeignKey(
                blank=True,
                db_column="ALG_recorder_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_allergies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="asserter",
            field=models.ForeignKey(
                blank=True,
                db_column="COND_asserter_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asserted_conditions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                db_column="COND_encounter_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conditions",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="patient",
            field=models.ForeignKey(
                db_column="COND_patient_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="recorder",
            field=models.ForeignKey(
                blank=True,
                db_column="COND_recorder_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_conditions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
