# Generated by Django 6.0.2 on 2026-02-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAH4PCTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('target_provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wah4pc_transaction',
            },
        ),
    ]
