# Generated by Django 6.0.2 on 2026-02-17 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_allergyintolerance_encounter_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="philhealth_id",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="PhilHealth ID must follow the format XX-XXXXXXXXX-X (e.g. 12-345678901-2).",
                        regex="^\\d{2}-\\d{9}-\\d$",
                    )
                ],
            ),
        ),
    ]
