# Generated by Django 6.0.2 on 2026-02-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_wah4pctransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
