# Generated by Django 6.0.2 on 2026-02-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_philhealth_id_format_validator"),
    ]

    operations = [
        migrations.AddField(
            model_name="wah4pctransaction",
            name="raw_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wah4pctransaction",
            name="related_patient",
            field=models.ForeignKey(
                blank=True,
                db_column="related_patient_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="wah4pctransaction",
            name="requester_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="wah4pctransaction",
            name="sender_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
