# Generated by Django 6.0.2 on 2026-02-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
