# Generated by Django 6.0.2 on 2026-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_wah4pc_transaction_audit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="immunization",
            name="performer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
