# Generated by Django 6.0.2 on 2026-02-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wah4pctransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
