# Generated by Django 6.0 on 2025-12-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("admission_date", models.DateTimeField()),
                (
                    "encounter_type",
                    models.CharField(default="Inpatient", max_length=50),
                ),
                ("admitting_diagnosis", models.CharField(max_length=255)),
                ("reason_for_admission", models.TextField()),
                ("ward", models.CharField(max_length=50)),
                ("room", models.CharField(max_length=20)),
                ("bed", models.CharField(max_length=10)),
                ("attending_physician", models.CharField(max_length=100)),
                ("assigned_nurse", models.CharField(blank=True, max_length=100)),
                (
                    "admission_category",
                    models.CharField(
                        choices=[("Regular", "Regular"), ("Emergency", "Emergency")],
                        default="Regular",
                        max_length=20,
                    ),
                ),
                (
                    "mode_of_arrival",
                    models.CharField(
                        choices=[
                            ("Walk-in", "Walk-in"),
                            ("Ambulance", "Ambulance"),
                            ("Referral", "Referral"),
                        ],
                        default="Walk-in",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Discharged", "Discharged"),
                            ("Transferred", "Transferred"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
