# Generated by Django 6.0 on 2025-12-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="admission_id",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
