# Generated by Django 6.0.1 on 2026-01-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("admission", "0002_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_code", models.CharField(blank=True, max_length=100, null=True)),
                ("item_name", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_stock",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reorder_level",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unit_of_measure",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit_cost", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "last_restocked_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "inventory",
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medication_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "code_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "code_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "implicit_rules",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "medication",
            },
        ),
        migrations.CreateModel(
            name="MedicationRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "medication_request_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("based_on_id", models.IntegerField(blank=True, null=True)),
                ("insurance_id", models.IntegerField(blank=True, null=True)),
                ("reported_reference_id", models.IntegerField(blank=True, null=True)),
                ("reason_reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "medication_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "medication_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "medication_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "medication_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("intent", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("priority", models.CharField(blank=True, max_length=255, null=True)),
                ("do_not_perform", models.BooleanField(blank=True, null=True)),
                ("reported_boolean", models.BooleanField(blank=True, null=True)),
                ("authored_on", models.DateTimeField(blank=True, null=True)),
                (
                    "status_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("dosage_text", models.TextField(blank=True, null=True)),
                (
                    "dosage_site",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_route",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_dose_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dosage_dose_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_rate_quantity_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dosage_rate_quantity_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dosage_rate_ratio_numerator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_rate_ratio_denominator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dispense_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dispense_initial_fill_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dispense_initial_fill_duration",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dispense_interval",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dispense_validity_period_start",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dispense_validity_period_end",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dispense_repeats_allowed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "group_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "course_of_therapy_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instantiates_canonical",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instantiates_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performer_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admission.encounter",
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        blank=True,
                        db_column="performer_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medication_requests_performed",
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        blank=True,
                        db_column="recorder_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medication_requests_recorded",
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        db_column="requester_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medication_requests_requested",
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "medication_request",
            },
        ),
        migrations.CreateModel(
            name="MedicationAdministration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "medication_administration_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("context_id", models.IntegerField(blank=True, null=True)),
                ("part_of_id", models.IntegerField(blank=True, null=True)),
                ("device_id", models.IntegerField(blank=True, null=True)),
                ("event_history_id", models.IntegerField(blank=True, null=True)),
                ("reason_reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "medication_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "medication_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "medication_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "medication_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instantiates_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("effective_datetime", models.DateTimeField(blank=True, null=True)),
                ("effective_period_start", models.DateField(blank=True, null=True)),
                ("effective_period_end", models.DateField(blank=True, null=True)),
                (
                    "performer_function",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("dosage_text", models.TextField(blank=True, null=True)),
                (
                    "dosage_site",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_route",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_dose_value",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "dosage_dose_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_rate_quantity_value",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "dosage_rate_quantity_unit",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "dosage_rate_ratio_numerator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dosage_rate_ratio_denominator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performer_actor",
                    models.ForeignKey(
                        blank=True,
                        db_column="performer_actor_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        db_column="request_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.medicationrequest",
                    ),
                ),
            ],
            options={
                "db_table": "medication_administration",
            },
        ),
    ]
