# Generated by Django 6.0 on 2026-01-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicationrequest",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medication_requests",
                to="admissions.admission",
            ),
        ),
    ]
