# Generated by Django 6.0.2 on 2026-02-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
