# Generated by Django 6.0.1 on 2026-01-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
        ("pharmacy", "0002_alter_medicationrequest_admission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispenselog",
            options={"ordering": ["-dispensed_at"]},
        ),
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="medicationrequest",
            options={"ordering": ["-requested_at"]},
        ),
        migrations.AddField(
            model_name="dispenselog",
            name="dispensed_by",
            field=models.CharField(
                blank=True,
                help_text="Pharmacist who dispensed the medication",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dispenselog",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive items are not available for dispensing",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="minimum_stock_level",
            field=models.PositiveIntegerField(
                default=10, help_text="Alert when stock falls below this level"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price per unit for billing",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="medicationrequest",
            name="approved_by",
            field=models.CharField(
                blank=True,
                help_text="Pharmacist who approved/denied the request",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="medicationrequest",
            name="requested_by",
            field=models.CharField(
                blank=True,
                help_text="Healthcare provider who requested the medication",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="batch_number",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="brand_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="generic_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="medicationrequest",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medication_requests",
                to="pharmacy.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="medicationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("dispensed", "Dispensed"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["generic_name", "batch_number"],
                name="pharmacy_in_generic_07e50d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["expiry_date"], name="pharmacy_in_expiry__3ec446_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationrequest",
            index=models.Index(
                fields=["status", "-requested_at"], name="pharmacy_me_status_c13f3a_idx"
            ),
        ),
    ]
