# Generated by Django 5.2.7 on 2026-02-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_inventory_description_inventory_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrequest',
            name='billing_reference',
            field=models.CharField(blank=True, help_text='Reference to the Claim/Invoice generated', max_length=100, null=True),
        ),
    ]
