# Generated by Django 5.2.7 on 2026-02-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicationrequest_billing_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationrequest',
            name='billing_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Reference to the Claim/Invoice generated', max_length=100, null=True),
        ),
    ]
