# Generated by Django 6.0 on 2025-12-19 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("room", models.CharField(blank=True, max_length=50, null=True)),
                ("admitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Vitals", "Vitals"),
                            ("Note", "Note"),
                            ("Medication", "Medication"),
                            ("Lab", "Lab"),
                            ("Procedure", "Procedure"),
                            ("Admission", "Admission"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="monitoring.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DietaryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_plan", models.CharField(max_length=255)),
                (
                    "activity_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("npo", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dietary_orders",
                        to="monitoring.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SOAP", "SOAP"),
                            ("Progress", "Progress"),
                            ("Rounds", "Rounds"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("staff_name", models.CharField(max_length=100)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="monitoring.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_pressure", models.CharField(max_length=20)),
                ("heart_rate", models.IntegerField()),
                ("respiratory_rate", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("oxygen_saturation", models.FloatField()),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("staff_name", models.CharField(max_length=100)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="monitoring.patient",
                    ),
                ),
            ],
        ),
    ]
