# Generated by Django 6.0.2 on 2026-02-18 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargeItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("chargeitem_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_id", models.BigIntegerField(db_index=True)),
                (
                    "account_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "context_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("partof_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "performing_organization_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "requesting_organization_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("performer_actor_id", models.BigIntegerField(blank=True, null=True)),
                ("enterer_id", models.BigIntegerField(blank=True, null=True)),
                ("cost_center_id", models.BigIntegerField(blank=True, null=True)),
                ("code", models.CharField(db_index=True, max_length=100)),
                (
                    "definition_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "definition_canonical",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "occurrence_datetime",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("occurrence_period_start", models.DateField(blank=True, null=True)),
                ("occurrence_period_end", models.DateField(blank=True, null=True)),
                ("entered_date", models.DateTimeField(blank=True, null=True)),
                (
                    "performer_function",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bodysite_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bodysite_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "factor_override",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price_override_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "price_override_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "override_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_codeableconcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quantity_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "quantity_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "supporting_information",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "monitoring_charge_item",
                "indexes": [
                    models.Index(
                        fields=["subject_id", "occurrence_datetime"],
                        name="chg_subj_occ_idx",
                    ),
                    models.Index(
                        fields=["account_id", "status"], name="chg_acct_status_idx"
                    ),
                    models.Index(fields=["code", "status"], name="chg_code_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChargeItemDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "chargeitemdefinition_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("partOf_id", models.BigIntegerField(blank=True, null=True)),
                ("replaces_id", models.BigIntegerField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                ("version", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "derivedFromUri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experimental",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_telecom",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("usecontext_code", models.TextField(blank=True, null=True)),
                ("usecontext_value", models.TextField(blank=True, null=True)),
                (
                    "jurisdiction_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "jurisdiction_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("copyright", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "approvalDate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lastReviewDate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("effectivePeriod_start", models.DateField(blank=True, null=True)),
                ("effectivePeriod_end", models.DateField(blank=True, null=True)),
                ("code", models.CharField(db_index=True, max_length=100)),
                (
                    "instance_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("applicability_description", models.TextField(blank=True, null=True)),
                (
                    "applicability_language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "applicability_expression",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "monitoring_charge_item_definition",
                "indexes": [
                    models.Index(
                        fields=["code", "status"], name="chgdef_code_status_idx"
                    ),
                    models.Index(
                        fields=["effectivePeriod_start", "effectivePeriod_end"],
                        name="chgdef_eff_period_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("observation_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_id", models.BigIntegerField(db_index=True)),
                ("encounter_id", models.BigIntegerField(db_index=True)),
                (
                    "performer_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("specimen_id", models.BigIntegerField(blank=True, null=True)),
                ("device_id", models.BigIntegerField(blank=True, null=True)),
                ("derived_from_id", models.BigIntegerField(blank=True, null=True)),
                ("focus_id", models.BigIntegerField(blank=True, null=True)),
                ("has_member_id", models.BigIntegerField(blank=True, null=True)),
                ("code", models.CharField(db_index=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("body_site", models.CharField(blank=True, max_length=255, null=True)),
                ("method", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "interpretation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_absent_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("based_on", models.CharField(blank=True, max_length=255, null=True)),
                ("part_of", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "value_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "value_integer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "value_codeableconcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_time", models.CharField(blank=True, max_length=255, null=True)),
                ("value_period_start", models.DateField(blank=True, null=True)),
                ("value_period_end", models.DateField(blank=True, null=True)),
                (
                    "value_ratio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_sampled_data",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reference_range_applies_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_age_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_age_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reference_range_text", models.TextField(blank=True, null=True)),
                (
                    "effective_datetime",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("effective_period_start", models.DateField(blank=True, null=True)),
                ("effective_period_end", models.DateField(blank=True, null=True)),
                (
                    "effective_timing",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "effective_instant",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issued", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "monitoring_observation",
                "indexes": [
                    models.Index(
                        fields=["subject_id", "effective_datetime"],
                        name="obs_subj_eff_idx",
                    ),
                    models.Index(
                        fields=["encounter_id", "code"], name="obs_enc_code_idx"
                    ),
                    models.Index(fields=["code", "status"], name="obs_code_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChargeItemDefinitionPriceComponent",
            fields=[
                (
                    "pricecomponent_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "factor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "amount_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "amount_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("applicability_description", models.TextField(blank=True, null=True)),
                (
                    "applicability_language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "applicability_expression",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "charge_item_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_components",
                        to="monitoring.chargeitemdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_charge_item_definition_price_component",
                "indexes": [
                    models.Index(
                        fields=["charge_item_definition", "type"],
                        name="chgdef_pc_def_type_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ObservationComponent",
            fields=[
                ("component_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=100)),
                (
                    "value_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "value_codeableconcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "value_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "value_integer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_ratio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_sampled_data",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("value_time", models.CharField(blank=True, max_length=255, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_period_start", models.DateField(blank=True, null=True)),
                ("value_period_end", models.DateField(blank=True, null=True)),
                (
                    "data_absent_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "interpretation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reference_range_text", models.TextField(blank=True, null=True)),
                (
                    "reference_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_age_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_age_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_applies_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="monitoring.observation",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_observation_component",
                "indexes": [
                    models.Index(
                        fields=["observation", "code"], name="obs_comp_obs_code_idx"
                    )
                ],
            },
        ),
    ]
