# Generated by Django 6.0.1 on 2026-01-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("admission", "0003_initial"),
        ("billing", "0001_initial"),
        ("laboratory", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("chargeitem_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100)),
                (
                    "definition_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "definition_canonical",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("occurrence_datetime", models.DateTimeField(blank=True, null=True)),
                ("occurrence_period_start", models.DateField(blank=True, null=True)),
                ("occurrence_period_end", models.DateField(blank=True, null=True)),
                ("entered_date", models.DateTimeField(blank=True, null=True)),
                (
                    "performer_function",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bodysite_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bodysite_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "factor_override",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price_override_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_override_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "override_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_codeableconcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quantity_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "quantity_unit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "supporting_information",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        db_column="account_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.account",
                    ),
                ),
                (
                    "context",
                    models.ForeignKey(
                        blank=True,
                        db_column="context_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_items",
                        to="admission.encounter",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        db_column="cost_center_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_center_charge_items",
                        to="accounts.organization",
                    ),
                ),
                (
                    "enterer",
                    models.ForeignKey(
                        blank=True,
                        db_column="enterer_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entered_charge_items",
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "partof",
                    models.ForeignKey(
                        blank=True,
                        db_column="partof_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_item_parts",
                        to="billing.account",
                    ),
                ),
                (
                    "performer_actor",
                    models.ForeignKey(
                        blank=True,
                        db_column="performer_actor_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "performing_organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="performing_organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_items_performed",
                        to="accounts.organization",
                    ),
                ),
                (
                    "requesting_organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="requesting_organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_items_requested",
                        to="accounts.organization",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "charge_item",
            },
        ),
        migrations.CreateModel(
            name="ChargeItemDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "chargeitemdefinition_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                ("version", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "derivedFromUri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experimental",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_telecom",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("usecontext_code", models.TextField(blank=True, null=True)),
                ("usecontext_value", models.TextField(blank=True, null=True)),
                (
                    "jurisdiction_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "jurisdiction_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("copyright", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "approvalDate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lastReviewDate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("effectivePeriod_start", models.DateField(blank=True, null=True)),
                ("effectivePeriod_end", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=100)),
                (
                    "instance_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("applicability_description", models.TextField(blank=True, null=True)),
                (
                    "applicability_language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "applicability_expression",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "propertyGroup_priceComponent_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "propertyGroup_priceComponent_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "propertyGroup_priceComponent_factor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "propertyGroup_priceComponent_amount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "propertyGroup_priceComponent_amount_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "propertyGroup_applicability_description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "propertyGroup_applicability_language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "propertyGroup_applicability_expression",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "partOf",
                    models.ForeignKey(
                        blank=True,
                        db_column="partOf_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="monitoring.chargeitemdefinition",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        db_column="replaces_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_by",
                        to="monitoring.chargeitemdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "charge_item_definition",
            },
        ),
        migrations.CreateModel(
            name="NutritionOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "nutrition_order_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "oral_diet_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "oral_diet_schedule",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "texture_modifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fluid_consistency_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("exclude_food_modifier", models.TextField(blank=True, null=True)),
                ("food_preference_modifier", models.TextField(blank=True, null=True)),
                (
                    "supplement_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplement_product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_column="encounter_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admission.encounter",
                    ),
                ),
                (
                    "orderer",
                    models.ForeignKey(
                        blank=True,
                        db_column="orderer_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "nutrition_order",
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("observation_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("body_site", models.CharField(blank=True, max_length=255, null=True)),
                ("method", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "interpretation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_absent_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "value_integer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "value_codeableconcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_time", models.CharField(blank=True, max_length=255, null=True)),
                ("value_period_start", models.DateField(blank=True, null=True)),
                ("value_period_end", models.DateField(blank=True, null=True)),
                (
                    "value_ratio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_sampled_data",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "component_value_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "component_value_codeableconcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "component_value_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("component_value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "component_value_integer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_value_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_value_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_value_ratio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_value_sampled_data",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_value_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_value_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "component_value_period_start",
                    models.DateField(blank=True, null=True),
                ),
                ("component_value_period_end", models.DateField(blank=True, null=True)),
                (
                    "component_data_absent_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_interpretation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_reference_range_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "component_reference_range_text",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "component_reference_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_reference_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_reference_range_age_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_reference_range_age_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "component_reference_range_applies_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reference_range_applies_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_age_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_range_age_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reference_range_text", models.TextField(blank=True, null=True)),
                ("effective_datetime", models.DateTimeField(blank=True, null=True)),
                ("effective_period_start", models.DateField(blank=True, null=True)),
                ("effective_period_end", models.DateField(blank=True, null=True)),
                (
                    "effective_timing",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "effective_instant",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issued", models.DateTimeField(blank=True, null=True)),
                ("part_of", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "derived_from",
                    models.ForeignKey(
                        blank=True,
                        db_column="derived_from_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_observations",
                        to="monitoring.observation",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        db_column="device_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="admission.device",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admission.encounter",
                    ),
                ),
                (
                    "focus",
                    models.ForeignKey(
                        blank=True,
                        db_column="focus_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="focused_observations",
                        to="patients.patient",
                    ),
                ),
                (
                    "has_member",
                    models.ForeignKey(
                        blank=True,
                        db_column="has_member_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_of",
                        to="monitoring.observation",
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        blank=True,
                        db_column="performer_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        blank=True,
                        db_column="specimen_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="laboratory.specimen",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "observation",
            },
        ),
    ]
