# Generated by Django 6.0.1 on 2026-01-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("admission", "0002_initial"),
        ("monitoring", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargeitem",
            name="subject",
            field=models.ForeignKey(
                db_column="subject_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="encounter",
            field=models.ForeignKey(
                db_column="encounter_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="admission.encounter",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="performer",
            field=models.ForeignKey(
                blank=True,
                db_column="performer_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="subject",
            field=models.ForeignKey(
                db_column="subject_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="patients.patient",
            ),
        ),
    ]
