# Generated by Django 5.2.7 on 2026-02-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='billing_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Reference to the Claim/Invoice generated', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], db_index=True, default='routine', help_text='Observation priority level', max_length=20),
        ),
        migrations.AddField(
            model_name='observation',
            name='requester_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Doctor/Nurse who ordered the observation', null=True),
        ),
    ]
