# Generated by Django 6.0.1 on 2026-01-27 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("admission", "0002_initial"),
        ("monitoring", "0002_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nutrition_order_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "oral_diet_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "oral_diet_schedule",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "texture_modifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fluid_consistency_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("exclude_food_modifier", models.TextField(blank=True, null=True)),
                ("food_preference_modifier", models.TextField(blank=True, null=True)),
                (
                    "supplement_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplement_product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_column="encounter_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admission.encounter",
                    ),
                ),
                (
                    "orderer",
                    models.ForeignKey(
                        blank=True,
                        db_column="orderer_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.practitioner",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "nutrition_order",
            },
        ),
    ]
