# Generated by Django 6.0 on 2026-01-05 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DischargeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=255)),
                ("room", models.CharField(max_length=50)),
                ("admission_date", models.DateField()),
                ("condition", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("discharged", "Discharged"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("physician", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("estimated_discharge", models.DateField(blank=True, null=True)),
                ("final_diagnosis", models.BooleanField(default=False)),
                ("physician_signature", models.BooleanField(default=False)),
                ("medication_reconciliation", models.BooleanField(default=False)),
                ("discharge_summary", models.BooleanField(default=False)),
                ("billing_clearance", models.BooleanField(default=False)),
                ("nursing_notes", models.BooleanField(default=False)),
                ("follow_up_scheduled", models.BooleanField(default=False)),
                ("discharge_date", models.DateTimeField(blank=True, null=True)),
                ("final_diagnosis_text", models.TextField(blank=True)),
                ("discharge_summary_text", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_plan", models.TextField(blank=True)),
                ("hospital_stay_summary", models.TextField(blank=True)),
                ("discharge_medications", models.TextField(blank=True)),
                ("discharge_instructions", models.TextField(blank=True)),
                ("billing_status", models.CharField(blank=True, max_length=100)),
                ("pending_items", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_records",
                        to="admissions.admission",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
