# Generated by Django 6.0.2 on 2026-02-18 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discharge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discharge_id", models.AutoField(primary_key=True, serialize=False)),
                ("encounter_id", models.BigIntegerField(db_index=True)),
                ("patient_id", models.BigIntegerField(db_index=True)),
                (
                    "physician_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("discharge_datetime", models.DateTimeField(blank=True, null=True)),
                ("notice_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_cleared_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "workflow_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("summary_of_stay", models.TextField(blank=True, null=True)),
                ("discharge_instructions", models.TextField(blank=True, null=True)),
                ("pending_items", models.TextField(blank=True, null=True)),
                (
                    "follow_up_plan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "discharge_summary",
                "indexes": [
                    models.Index(
                        fields=["encounter_id"], name="discharge_s_encount_334a7a_idx"
                    ),
                    models.Index(
                        fields=["patient_id"], name="discharge_s_patient_9764b0_idx"
                    ),
                    models.Index(
                        fields=["workflow_status"],
                        name="discharge_s_workflo_9a9d1a_idx",
                    ),
                    models.Index(
                        fields=["discharge_datetime"],
                        name="discharge_s_dischar_0c6bd2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("procedure_id", models.AutoField(primary_key=True, serialize=False)),
                ("encounter_id", models.BigIntegerField(db_index=True)),
                ("subject_id", models.BigIntegerField(db_index=True)),
                (
                    "asserter_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "based_on_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "part_of_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "location_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "recorder_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "report_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "reason_reference_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "complication_detail_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "focal_device_manipulated_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "used_reference_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "instantiates_canonical",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instantiates_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status_reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status_reason_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("code_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "body_site_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "body_site_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "outcome_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "outcome_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_code_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "complication_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "complication_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "follow_up_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "follow_up_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "focal_device_action_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "focal_device_action_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "used_code_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "used_code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "performer_actor_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "performer_function_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "performer_function_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "performer_on_behalf_of_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("performed_datetime", models.DateTimeField(blank=True, null=True)),
                ("performed_period_start", models.DateField(blank=True, null=True)),
                ("performed_period_end", models.DateField(blank=True, null=True)),
                (
                    "performed_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_age_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_age_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "discharge_procedure",
                "indexes": [
                    models.Index(
                        fields=["identifier"], name="discharge_p_identif_fc334e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="discharge_p_status_29ab28_idx"
                    ),
                    models.Index(
                        fields=["encounter_id"], name="discharge_p_encount_3b2bd7_idx"
                    ),
                    models.Index(
                        fields=["subject_id"], name="discharge_p_subject_689596_idx"
                    ),
                    models.Index(
                        fields=["code_code"], name="discharge_p_code_co_3d85fb_idx"
                    ),
                    models.Index(
                        fields=["performed_datetime"],
                        name="discharge_p_perform_f42299_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcedurePerformer",
            fields=[
                (
                    "procedure_performer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "performer_actor_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "performer_on_behalf_of_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "performer_function_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "performer_function_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "procedure",
                    models.ForeignKey(
                        db_column="procedure_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performers",
                        to="discharge.procedure",
                    ),
                ),
            ],
            options={
                "db_table": "discharge_procedure_performer",
                "indexes": [
                    models.Index(
                        fields=["procedure_id"], name="discharge_p_procedu_b16e7d_idx"
                    ),
                    models.Index(
                        fields=["performer_actor_id"],
                        name="discharge_p_perform_30af16_idx",
                    ),
                ],
            },
        ),
    ]
