# Generated by Django 6.0.1 on 2026-01-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discharge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discharge_id", models.AutoField(primary_key=True, serialize=False)),
                ("discharge_datetime", models.DateTimeField(blank=True, null=True)),
                ("discharge_instructions", models.TextField(blank=True, null=True)),
                ("summary_of_stay", models.TextField(blank=True, null=True)),
                ("pending_items", models.TextField(blank=True, null=True)),
                (
                    "follow_up_plan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "workflow_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notice_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "billing_cleared_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admission.encounter",
                    ),
                ),
            ],
            options={
                "db_table": "discharge",
            },
        ),
    ]
