# Generated by Django 5.2.7 on 2026-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='final_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
