# Generated by Django 6.0.1 on 2026-01-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("discharge", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discharge",
            name="patient",
            field=models.ForeignKey(
                db_column="patient_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="discharge",
            name="physician",
            field=models.ForeignKey(
                blank=True,
                db_column="physician_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.practitioner",
            ),
        ),
    ]
