# Generated by Django 6.0.1 on 2026-01-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "appointment",
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("encounter_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_field",
                    models.CharField(
                        blank=True, db_column="class", max_length=100, null=True
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("priority", models.CharField(blank=True, max_length=100, null=True)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "length_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("length_unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hospitalization_admit_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hospitalization_re_admission",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "hospitalization_diet_preference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hospitalization_special_courtesy",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hospitalization_special_arrangement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hospitalization_discharge_disposition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("location_period_start", models.DateTimeField(blank=True, null=True)),
                ("location_period_end", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "encounter",
            },
        ),
        migrations.CreateModel(
            name="EpisodeOfCare",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "episode_of_care_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "episode_of_care",
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("procedure_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "instantiates_canonical",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instantiates_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("code_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("performed_datetime", models.DateTimeField(blank=True, null=True)),
                ("performed_period_start", models.DateTimeField(blank=True, null=True)),
                ("performed_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "performed_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("performed_age", models.IntegerField(blank=True, null=True)),
                (
                    "performed_range",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("body_site", models.CharField(blank=True, max_length=255, null=True)),
                ("outcome", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "complication",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("follow_up", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("used_code", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "procedure",
            },
        ),
        migrations.CreateModel(
            name="ProcedurePerformer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "procedure_performer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("function", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "procedure_performer",
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "service_request_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("intent", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "service_request",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.CharField(blank=True, max_length=100, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_devices",
                        to="accounts.location",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_devices",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "device",
            },
        ),
    ]
