# Generated by Django 6.0.2 on 2026-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "admission_appointment",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("identifier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("model", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.CharField(blank=True, max_length=100, null=True)),
                ("patient_id", models.IntegerField(blank=True, null=True)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                ("location_id", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "admission_device",
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("encounter_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_field",
                    models.CharField(
                        blank=True,
                        db_column="class",
                        help_text="Class of encounter (inpatient, outpatient, emergency, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("priority", models.CharField(blank=True, max_length=255, null=True)),
                ("subject_patient_id", models.IntegerField()),
                ("episode_of_care_id", models.IntegerField(blank=True, null=True)),
                (
                    "based_on_service_request_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("appointment_id", models.IntegerField(blank=True, null=True)),
                (
                    "participant_individual_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "participant_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("length", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason_reference_id", models.IntegerField(blank=True, null=True)),
                ("diagnosis_condition_id", models.IntegerField(blank=True, null=True)),
                (
                    "diagnosis_rank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "diagnosis_use",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location_id", models.IntegerField(blank=True, null=True)),
                (
                    "location_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("location_period_start", models.DateField(blank=True, null=True)),
                ("location_period_end", models.DateField(blank=True, null=True)),
                (
                    "location_physical_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "admit_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("re_admission", models.BooleanField(blank=True, null=True)),
                (
                    "diet_preference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "special_courtesy",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "special_arrangement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discharge_destination_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("discharge_disposition", models.TextField(blank=True, null=True)),
                ("service_provider_id", models.IntegerField(blank=True, null=True)),
                ("account_id", models.IntegerField(blank=True, null=True)),
                ("part_of_encounter_id", models.IntegerField(blank=True, null=True)),
                (
                    "pre_admission_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Encounter",
                "verbose_name_plural": "Encounters",
                "db_table": "encounter",
            },
        ),
        migrations.CreateModel(
            name="EpisodeOfCare",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episode_of_care_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("identifier", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("patient_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "admission_episode_of_care",
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("procedure_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status_reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status_reason_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instantiates_canonical",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instantiates_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("based_on_id", models.IntegerField(blank=True, null=True)),
                ("part_of_id", models.IntegerField(blank=True, null=True)),
                (
                    "category_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("code_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("subject_id", models.IntegerField()),
                ("encounter_id", models.IntegerField()),
                ("performed_datetime", models.DateTimeField(blank=True, null=True)),
                ("performed_period_start", models.DateField(blank=True, null=True)),
                ("performed_period_end", models.DateField(blank=True, null=True)),
                (
                    "performed_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_age_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_age_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("performer_actor_id", models.IntegerField(blank=True, null=True)),
                (
                    "performer_function_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "performer_function_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "performer_on_behalf_of_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("recorder_id", models.IntegerField(blank=True, null=True)),
                ("asserter_id", models.IntegerField(blank=True, null=True)),
                ("location_id", models.IntegerField(blank=True, null=True)),
                (
                    "reason_code_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason_reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "body_site_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "body_site_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "outcome_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "outcome_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "complication_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "complication_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("complication_detail_id", models.IntegerField(blank=True, null=True)),
                (
                    "follow_up_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "follow_up_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("report_id", models.IntegerField(blank=True, null=True)),
                (
                    "focal_device_manipulated_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "focal_device_action_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "focal_device_action_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("used_reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "used_code_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "used_code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Procedure",
                "verbose_name_plural": "Procedures",
                "db_table": "procedure",
            },
        ),
        migrations.CreateModel(
            name="ProcedurePerformer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "procedure_performer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("procedure_id", models.IntegerField()),
                (
                    "status_reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status_reason_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "instantiates_canonical",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instantiates_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("based_on_id", models.IntegerField(blank=True, null=True)),
                ("part_of_id", models.IntegerField(blank=True, null=True)),
                (
                    "category_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("code_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("subject_id", models.IntegerField()),
                ("encounter_id", models.IntegerField()),
                ("performed_datetime", models.DateTimeField(blank=True, null=True)),
                ("performed_period_start", models.DateField(blank=True, null=True)),
                ("performed_period_end", models.DateField(blank=True, null=True)),
                (
                    "performed_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_age_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_age_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_range_low",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_range_high",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("performer_actor_id", models.IntegerField(blank=True, null=True)),
                (
                    "performer_function_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "performer_function_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "performer_on_behalf_of_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("recorder_id", models.IntegerField(blank=True, null=True)),
                ("asserter_id", models.IntegerField(blank=True, null=True)),
                ("location_id", models.IntegerField(blank=True, null=True)),
                (
                    "reason_code_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reason_code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason_reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "body_site_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "body_site_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "outcome_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "outcome_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "complication_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "complication_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("complication_detail_id", models.IntegerField(blank=True, null=True)),
                (
                    "follow_up_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "follow_up_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("report_id", models.IntegerField(blank=True, null=True)),
                (
                    "focal_device_manipulated_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "focal_device_action_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "focal_device_action_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("used_reference_id", models.IntegerField(blank=True, null=True)),
                (
                    "used_code_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "used_code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Procedure Performer",
                "verbose_name_plural": "Procedure Performers",
                "db_table": "procedure_performer",
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_request_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("identifier", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("intent", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("subject_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "admission_service_request",
            },
        ),
    ]
