# Generated by Django 6.0.1 on 2026-01-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("encounter_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "class_field",
                    models.CharField(
                        blank=True, db_column="class", max_length=100, null=True
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("priority", models.CharField(blank=True, max_length=100, null=True)),
                ("episode_of_care_id", models.IntegerField(blank=True, null=True)),
                ("based_on_id", models.IntegerField(blank=True, null=True)),
                ("participant_id", models.IntegerField(blank=True, null=True)),
                ("appointment_id", models.IntegerField(blank=True, null=True)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "length_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("length_unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("account_id", models.IntegerField(blank=True, null=True)),
                (
                    "hospitalization_admit_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hospitalization_re_admission",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "hospitalization_diet_preference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hospitalization_special_courtesy",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hospitalization_special_arrangement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hospitalization_destination_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "hospitalization_discharge_disposition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("location_period_start", models.DateTimeField(blank=True, null=True)),
                ("location_period_end", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "encounter",
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("procedure_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "instantiates_canonical",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instantiates_uri",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("based_on_id", models.IntegerField(blank=True, null=True)),
                ("part_of_id", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=100)),
                (
                    "status_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("code_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("performed_datetime", models.DateTimeField(blank=True, null=True)),
                ("performed_period_start", models.DateTimeField(blank=True, null=True)),
                ("performed_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "performed_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("performed_age", models.IntegerField(blank=True, null=True)),
                (
                    "performed_range",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("performer_id", models.IntegerField(blank=True, null=True)),
                (
                    "reason_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason_reference_id", models.IntegerField(blank=True, null=True)),
                ("body_site", models.CharField(blank=True, max_length=255, null=True)),
                ("outcome", models.CharField(blank=True, max_length=255, null=True)),
                ("report_id", models.IntegerField(blank=True, null=True)),
                (
                    "complication",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("complication_detail_id", models.IntegerField(blank=True, null=True)),
                ("follow_up", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("focal_device_id", models.IntegerField(blank=True, null=True)),
                ("used_reference_id", models.IntegerField(blank=True, null=True)),
                ("used_code", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "procedure",
            },
        ),
        migrations.CreateModel(
            name="ProcedurePerformer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "procedure_performer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("function", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "procedure_performer",
            },
        ),
    ]
