# Generated by Django 6.0.2 on 2026-02-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='location_physical_type',
        ),
        migrations.AddField(
            model_name='encounter',
            name='location_ids',
            field=models.JSONField(blank=True, help_text='Hierarchical location path IDs [Building, Ward, Room, Bed]', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='location_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='location_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='location_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
