# Generated by Django 6.0.1 on 2026-01-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("admission", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encounter",
            name="diagnosis_condition",
            field=models.ForeignKey(
                blank=True,
                db_column="diagnosis_condition_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diagnosis_encounters",
                to="patients.condition",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="location_location",
            field=models.ForeignKey(
                blank=True,
                db_column="location_location_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.location",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="part_of_encounter",
            field=models.ForeignKey(
                blank=True,
                db_column="part_of_encounter_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="admission.encounter",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="service_provider_organization",
            field=models.ForeignKey(
                blank=True,
                db_column="service_provider_organization_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="subject_patient",
            field=models.ForeignKey(
                db_column="subject_patient_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="asserter",
            field=models.ForeignKey(
                blank=True,
                db_column="asserter_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asserted_procedures",
                to="accounts.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="encounter",
            field=models.ForeignKey(
                db_column="encounter_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="admission.encounter",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_column="location_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.location",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="recorder",
            field=models.ForeignKey(
                blank=True,
                db_column="recorder_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="subject",
            field=models.ForeignKey(
                db_column="subject_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="procedureperformer",
            name="on_behalf_of_organization",
            field=models.ForeignKey(
                blank=True,
                db_column="on_behalf_of_organization_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="procedureperformer",
            name="performer_actor",
            field=models.ForeignKey(
                db_column="performer_actor_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="procedureperformer",
            name="procedure",
            field=models.ForeignKey(
                db_column="procedure_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="admission.procedure",
            ),
        ),
    ]
