# Generated by Django 6.0.1 on 2026-01-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admission", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_column="patient_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="patients.patient",
            ),
        ),
    ]
