# Generated by Django 6.0.1 on 2026-01-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("admission", "0003_initial"),
        ("laboratory", "0001_initial"),
        ("patients", "0001_initial"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="report",
            field=models.ForeignKey(
                blank=True,
                db_column="report_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procedures",
                to="laboratory.diagnosticreport",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="subject",
            field=models.ForeignKey(
                db_column="subject_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="used_reference",
            field=models.ForeignKey(
                blank=True,
                db_column="used_reference_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_procedures",
                to="pharmacy.medication",
            ),
        ),
        migrations.AddField(
            model_name="procedureperformer",
            name="on_behalf_of_organization",
            field=models.ForeignKey(
                blank=True,
                db_column="on_behalf_of_organization_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="procedureperformer",
            name="performer_actor",
            field=models.ForeignKey(
                db_column="performer_actor_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.practitioner",
            ),
        ),
        migrations.AddField(
            model_name="procedureperformer",
            name="procedure",
            field=models.ForeignKey(
                db_column="procedure_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="admission.procedure",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                db_column="subject_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="based_on",
            field=models.ForeignKey(
                blank=True,
                db_column="based_on_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="based_procedures",
                to="admission.servicerequest",
            ),
        ),
        migrations.AddField(
            model_name="encounter",
            name="based_on",
            field=models.ForeignKey(
                blank=True,
                db_column="based_on_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="based_encounters",
                to="admission.servicerequest",
            ),
        ),
    ]
