# Generated by Django 6.0.1 on 2026-02-01 14:31

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("endpoint_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "connection_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_telecom",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "payload_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payload_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "endpoint",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "organization_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField(blank=True, null=True)),
                (
                    "nhfr_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("type_code", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("telecom", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_postal_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "contact_purpose",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_first_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_telecom",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_address_line",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_address_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_address_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_address_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_postal_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        db_column="endpoint_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizations",
                        to="accounts.endpoint",
                    ),
                ),
                (
                    "part_of_organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="part_of_organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_organizations",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "physical_type_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mode", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("telecom", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.CharField(blank=True, max_length=255, null=True)),
                ("altitude", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_postal_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "hours_of_operation_days",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hours_of_operation_all_day",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "opening_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "closing_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "availability_exceptions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        db_column="endpoint_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="accounts.endpoint",
                    ),
                ),
                (
                    "part_of_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="part_of_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.location",
                    ),
                ),
                (
                    "managing_organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="managing_organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "location",
            },
        ),
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "practitioner_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("active", models.BooleanField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                (
                    "suffix_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=100, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True, max_length=255, null=True)),
                ("telecom", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "communication_language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_postal_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "qualification_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "qualification_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("qualification_period_start", models.DateField(blank=True, null=True)),
                ("qualification_period_end", models.DateField(blank=True, null=True)),
                (
                    "qualification_issuer",
                    models.ForeignKey(
                        blank=True,
                        db_column="qualification_issuer_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qualified_practitioners",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "practitioner",
            },
        ),
        migrations.CreateModel(
            name="HealthcareService",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "healthcare_service_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("specialty", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("telecom", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "availability_exceptions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="healthcare_services",
                        to="accounts.location",
                    ),
                ),
                (
                    "provided_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="provided_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="healthcare_services",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "healthcare_service",
            },
        ),
        migrations.AddField(
            model_name="endpoint",
            name="managing_organization",
            field=models.ForeignKey(
                blank=True,
                db_column="managing_organization_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_endpoints",
                to="accounts.organization",
            ),
        ),
        migrations.CreateModel(
            name="PractitionerRole",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "practitioner_role_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("active", models.BooleanField(blank=True, null=True)),
                ("role_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "specialty_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telecom", models.CharField(blank=True, max_length=50, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "available_days_of_week",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("available_all_day_flag", models.BooleanField(blank=True, null=True)),
                (
                    "available_start_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "available_end_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "availability_exceptions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("not_available_description", models.TextField(blank=True, null=True)),
                ("not_available_period_start", models.DateField(blank=True, null=True)),
                ("not_available_period_end", models.DateField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        db_column="endpoint_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_roles",
                        to="accounts.endpoint",
                    ),
                ),
                (
                    "healthcare_service",
                    models.ForeignKey(
                        blank=True,
                        db_column="healthcare_service_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practitioner_roles",
                        to="accounts.healthcareservice",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.organization",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        db_column="practitioner_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.practitioner",
                    ),
                ),
            ],
            options={
                "db_table": "practitioner_role",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practitioner",
                    models.OneToOneField(
                        db_column="practitioner_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="accounts.practitioner",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "password",
                    models.CharField(db_column="password_hash", max_length=255),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=100)),
                ("id", models.IntegerField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
