# Generated by Django 6.0.1 on 2026-01-21 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="%(class)s_created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="%(class)s_updated_at"
                    ),
                ),
                (
                    "user_id",
                    models.AutoField(
                        db_column="USER_user_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_column="USER_username", max_length=50, unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_column="USER_is_active", default=True),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, db_column="USER_last_login", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "User Account",
                "verbose_name_plural": "User Accounts",
                "db_table": "USER",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="%(class)s_created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="%(class)s_updated_at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_column="%(class)s_status",
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "organization_id",
                    models.AutoField(
                        db_column="ORG_organization_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identifier_doh",
                    models.CharField(
                        blank=True,
                        db_column="ORG_identifier_doh",
                        help_text="Department of Health facility code",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "identifier_bir",
                    models.CharField(
                        blank=True,
                        db_column="ORG_identifier_bir",
                        help_text="Bureau of Internal Revenue TIN",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "identifier_nhfr",
                    models.CharField(
                        blank=True,
                        db_column="ORG_identifier_nhfr",
                        help_text="National Health Facility Registry code",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "identifier_phic",
                    models.CharField(
                        blank=True,
                        db_column="ORG_identifier_phic",
                        help_text="PhilHealth accreditation number",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_column="ORG_name", max_length=100)),
                (
                    "alias",
                    models.CharField(
                        blank=True, db_column="ORG_alias", max_length=100, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Hospital", "Hospital"),
                            ("Clinic", "Clinic"),
                            ("Laboratory", "Laboratory"),
                            ("Pharmacy", "Pharmacy"),
                            ("Other", "Other"),
                        ],
                        db_column="ORG_type",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        db_column="ORG_contact_number",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_column="ORG_email", max_length=100, null=True
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True,
                        db_column="ORG_street_address",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "barangay",
                    models.CharField(
                        blank=True, db_column="ORG_barangay", max_length=50, null=True
                    ),
                ),
                (
                    "city_municipality",
                    models.CharField(
                        blank=True,
                        db_column="ORG_city_municipality",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, db_column="ORG_province", max_length=50, null=True
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, db_column="ORG_region", max_length=50, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        db_column="ORG_postal_code",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_column="ORG_country", max_length=50, null=True
                    ),
                ),
                (
                    "extension_ownership_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("government", "Government"),
                            ("private", "Private"),
                            ("mixed", "Mixed"),
                        ],
                        db_column="ORG_extension_ownership_type",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "extension_service_category",
                    models.CharField(
                        blank=True,
                        db_column="ORG_extension_service_category",
                        help_text="Services offered (e.g., Primary Care, Tertiary)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="%(class)s_created_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "ORGANIZATION",
            },
        ),
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="%(class)s_created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="%(class)s_updated_at"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        db_column="%(class)s_gender",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "practitioner_id",
                    models.AutoField(
                        db_column="PRAC_practitioner_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identifier_license",
                    models.CharField(
                        blank=True,
                        db_column="PRAC_identifier_license",
                        help_text="Medical license number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "identifier_prc",
                    models.CharField(
                        blank=True,
                        db_column="PRAC_identifier_prc",
                        help_text="Professional Regulation Commission ID",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "identifier_ptr",
                    models.CharField(
                        blank=True,
                        db_column="PRAC_identifier_ptr",
                        help_text="Professional Tax Receipt",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "identifier_s2",
                    models.CharField(
                        blank=True,
                        db_column="PRAC_identifier_s2",
                        help_text="S2 License (for controlled substances)",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "identifier_employee",
                    models.CharField(
                        blank=True,
                        db_column="PRAC_identifier_employee",
                        help_text="Employee/Staff ID",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(db_column="PRAC_first_name", max_length=50),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        db_column="PRAC_middle_name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(db_column="PRAC_last_name", max_length=50),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, db_column="PRAC_suffix", max_length=10, null=True
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        db_column="PRAC_contact_number",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_column="PRAC_email",
                        help_text="Professional email (Single Source of Truth)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(db_column="PRAC_active", default=True)),
                (
                    "birthdate",
                    models.DateField(blank=True, db_column="PRAC_birthdate", null=True),
                ),
                (
                    "qualification_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Doctor", "Doctor"),
                            ("Nurse", "Nurse"),
                            ("Pharmacist", "Pharmacist"),
                            ("Admin", "Admin"),
                            ("Billing Staff", "Billing Staff"),
                            ("Lab Technician", "Lab Technician"),
                        ],
                        db_column="PRAC_qualification_code",
                        help_text="Primary qualification type",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "qualification_issuer",
                    models.CharField(
                        blank=True,
                        db_column="PRAC_qualification_issuer",
                        help_text="Issuing authority (e.g., PRC, DOH)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "qualification_valid_from",
                    models.DateField(
                        blank=True, db_column="PRAC_qualification_valid_from", null=True
                    ),
                ),
                (
                    "qualification_valid_to",
                    models.DateField(
                        blank=True, db_column="PRAC_qualification_valid_to", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="%(class)s_created_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="PRAC_user_id",
                        help_text="One-to-one link to authentication account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practitioner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner",
                "verbose_name_plural": "Practitioners",
                "db_table": "PRACTITIONER",
            },
        ),
        migrations.CreateModel(
            name="PractitionerRole",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="%(class)s_created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="%(class)s_updated_at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_column="%(class)s_status",
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "role_id",
                    models.AutoField(
                        db_column="PR_role_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("Doctor", "Doctor"),
                            ("Nurse", "Nurse"),
                            ("Pharmacist", "Pharmacist"),
                            ("Admin", "Admin"),
                            ("Billing Staff", "Billing Staff"),
                            ("Lab Technician", "Lab Technician"),
                        ],
                        db_column="PR_code",
                        help_text="Role type for authorization (CBAC)",
                        max_length=20,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        db_column="PR_specialty",
                        help_text="Medical specialty (e.g., Cardiology, Pediatrics)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        db_column="PR_period_start",
                        help_text="Role effective start date",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True,
                        db_column="PR_period_end",
                        help_text="Role expiration date (null = indefinite)",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="PR_organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practitioner_roles",
                        to="accounts.organization",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        db_column="PR_practitioner_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="accounts.practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner Role",
                "verbose_name_plural": "Practitioner Roles",
                "db_table": "PRACTITIONER_ROLE",
                "indexes": [
                    models.Index(
                        fields=["practitioner", "status"],
                        name="PRACTITIONE_PR_prac_4a55f7_idx",
                    ),
                    models.Index(
                        fields=["organization", "code"],
                        name="PRACTITIONE_PR_orga_8d7516_idx",
                    ),
                ],
            },
        ),
    ]
