# Generated by Django 6.0.1 on 2026-01-27 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practitioner_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("active", models.BooleanField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_name", models.CharField(max_length=255)),
                (
                    "suffix_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=100, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("photo_url", models.URLField(blank=True, max_length=255, null=True)),
                ("telecom", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "communication_language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_postal_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "qualification_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "qualification_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("qualification_issuer_id", models.IntegerField(blank=True, null=True)),
                ("qualification_period_start", models.DateField(blank=True, null=True)),
                ("qualification_period_end", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "practitioner",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practitioner",
                    models.OneToOneField(
                        db_column="practitioner_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="accounts.practitioner",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(max_length=100)),
                ("last_login", models.CharField(blank=True, max_length=255, null=True)),
                ("id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField(blank=True, null=True)),
                (
                    "nhfr_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("telecom", models.CharField(blank=True, max_length=50, null=True)),
                ("endpoint_id", models.IntegerField(blank=True, null=True)),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_postal_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "contact_purpose",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_first_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_last_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_telecom",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_address_line",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_address_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_address_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_address_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_address_postal_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "part_of_organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="part_of_organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_organizations",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "physical_type_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mode", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("telecom", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.CharField(blank=True, max_length=255, null=True)),
                ("altitude", models.CharField(blank=True, max_length=255, null=True)),
                ("endpoint_id", models.IntegerField(blank=True, null=True)),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_district",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_postal_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "hours_of_operation_days",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hours_of_operation_all_day",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "opening_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "closing_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "availability_exceptions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "part_of_location",
                    models.ForeignKey(
                        blank=True,
                        db_column="part_of_location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.location",
                    ),
                ),
                (
                    "managing_organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="managing_organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "location",
            },
        ),
        migrations.CreateModel(
            name="PractitionerRole",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practitioner_role_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("active", models.BooleanField(blank=True, null=True)),
                ("role_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "specialty_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telecom", models.CharField(blank=True, max_length=50, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "available_days_of_week",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("available_all_day_flag", models.BooleanField(blank=True, null=True)),
                (
                    "available_start_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "available_end_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "availability_exceptions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("not_available_description", models.TextField(blank=True, null=True)),
                ("not_available_period_start", models.DateField(blank=True, null=True)),
                ("not_available_period_end", models.DateField(blank=True, null=True)),
                ("endpoint_id", models.IntegerField(blank=True, null=True)),
                ("healthcare_service_id", models.IntegerField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_column="organization_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.organization",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        db_column="practitioner_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.practitioner",
                    ),
                ),
            ],
            options={
                "db_table": "practitioner_role",
            },
        ),
    ]
