# Generated by Django 6.0 on 2025-12-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=50),
        ),
    ]
