# Generated by Django 5.2.7 on 2025-10-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("civil_status", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("room", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("admission_date", models.DateField()),
                ("condition", models.CharField(max_length=255)),
                ("physician", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Admitted", "Admitted"),
                            ("Discharged", "Discharged"),
                            ("Transferred", "Transferred"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "philhealth_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
