# Generated by Django 5.2.11 on 2026-02-17 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(db_index=True, max_length=100)),
                ('imaging_study_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.BigIntegerField(db_index=True)),
                ('encounter_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('modality', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_series', models.IntegerField(blank=True, null=True)),
                ('number_of_instances', models.IntegerField(blank=True, null=True)),
                ('interpreter_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory_imaging_study',
            },
        ),
        migrations.CreateModel(
            name='LabTestDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(db_index=True, max_length=100)),
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnaround_time', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, help_text='Measurement unit (e.g. mg/dL)', max_length=50, null=True)),
                ('normal_range', models.JSONField(blank=True, default=dict, help_text="JSON structure for ranges, e.g. {'male': '13.5-17.5', 'female': '12.0-15.5'}")),
            ],
            options={
                'db_table': 'laboratory_test_definition',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(db_index=True, max_length=100)),
                ('specimen_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.BigIntegerField(db_index=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_datetime', models.DateTimeField(blank=True, null=True)),
                ('collection_method', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_body_site', models.CharField(blank=True, max_length=255, null=True)),
                ('collector_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('received_time', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory_specimen',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(db_index=True, max_length=100)),
                ('diagnostic_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.BigIntegerField(db_index=True)),
                ('encounter_id', models.BigIntegerField(db_index=True)),
                ('billing_reference', models.CharField(blank=True, db_index=True, help_text='Reference to the Claim/Invoice generated', max_length=100, null=True)),
                ('requester_id', models.BigIntegerField(blank=True, db_index=True, help_text='Doctor/Nurse who ordered the test (from Monitoring module)', null=True)),
                ('performer_id', models.BigIntegerField(blank=True, db_index=True, help_text='Lab technician who performed/processed the test', null=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], db_index=True, default='routine', help_text='Test priority level', max_length=20)),
                ('results_interpreter_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('specimen_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('based_on_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('imaging_study_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('code_code', models.CharField(blank=True, max_length=100, null=True)),
                ('code_display', models.CharField(blank=True, max_length=100, null=True)),
                ('category_code', models.CharField(blank=True, max_length=100, null=True)),
                ('category_display', models.CharField(blank=True, max_length=100, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=255, null=True)),
                ('conclusion_code', models.CharField(blank=True, max_length=100, null=True)),
                ('conclusion_display', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_datetime', models.DateTimeField(blank=True, null=True)),
                ('effective_period_start', models.DateField(blank=True, null=True)),
                ('effective_period_end', models.DateField(blank=True, null=True)),
                ('issued_datetime', models.DateTimeField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laboratory_diagnostic_report',
                'indexes': [models.Index(fields=['status', 'priority'], name='lab_status_priority_idx'), models.Index(fields=['encounter_id', 'status'], name='lab_encounter_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticReportResult',
            fields=[
                ('diagnostic_report_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_id', models.BigIntegerField(db_index=True)),
                ('item_sequence', models.IntegerField()),
                ('diagnostic_report', models.ForeignKey(db_column='diagnostic_report_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.diagnosticreport')),
            ],
            options={
                'db_table': 'laboratory_diagnostic_report_result',
                'ordering': ['item_sequence'],
            },
        ),
    ]
