# Generated by Django 6.0.1 on 2026-01-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("admission", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagingStudy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "imaging_study_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("modality", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("number_of_series", models.IntegerField(blank=True, null=True)),
                ("number_of_instances", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "imaging_study",
            },
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("specimen_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("collection_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "collection_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "collection_body_site",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("received_time", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "specimen",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "diagnostic_report_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("code_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "code_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("conclusion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "conclusion_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "conclusion_display",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("effective_datetime", models.DateTimeField(blank=True, null=True)),
                ("effective_period_start", models.DateField(blank=True, null=True)),
                ("effective_period_end", models.DateField(blank=True, null=True)),
                ("issued_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "media_comment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "presented_form_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "based_on",
                    models.ForeignKey(
                        blank=True,
                        db_column="based_on_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_reports",
                        to="admission.servicerequest",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        db_column="encounter_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admission.encounter",
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        blank=True,
                        db_column="performer_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_reports_performed",
                        to="accounts.practitioner",
                    ),
                ),
            ],
            options={
                "db_table": "diagnostic_report",
            },
        ),
    ]
