# Generated by Django 5.2.7 on 2026-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticreport',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], db_index=True, default='routine', help_text='Test priority level', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='requester_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Doctor/Nurse who ordered the test (from Monitoring module)', null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='performer_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Lab technician who performed/processed the test', null=True),
        ),
        migrations.AddIndex(
            model_name='diagnosticreport',
            index=models.Index(fields=['status', 'priority'], name='lab_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreport',
            index=models.Index(fields=['encounter_id', 'status'], name='lab_encounter_status_idx'),
        ),
    ]
