# Generated by Django 6.0 on 2026-01-02 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labrequest",
            name="specimen_collected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="specimen_collected_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["nurse", "lab_technician"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_specimens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="specimen_id",
            field=models.CharField(
                blank=True,
                help_text="Specimen barcode or tracking number",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="labrequest",
            name="specimen_type",
            field=models.CharField(
                blank=True,
                help_text="Type of specimen (e.g., Blood, Urine, Stool)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labresult",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Pathologist or senior technician who verified the results",
                limit_choices_to={"role__in": ["doctor", "lab_technician"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_lab_tests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="labrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("specimen_collected", "Specimen Collected"),
                    ("in_progress", "In Progress"),
                    ("for_verification", "For Verification"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
