# Generated by Django 6.0.1 on 2026-01-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("laboratory", "0001_initial"),
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticreport",
            name="result",
            field=models.ForeignKey(
                blank=True,
                db_column="result_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="monitoring.observation",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="results_interpreter",
            field=models.ForeignKey(
                blank=True,
                db_column="results_interpreter_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diagnostic_reports_interpreted",
                to="accounts.practitioner",
            ),
        ),
    ]
