# Generated by Django 6.0 on 2026-01-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0002_labrequest_specimen_collected_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labrequest",
            name="specimen_collected_at",
        ),
        migrations.RemoveField(
            model_name="labrequest",
            name="specimen_collected_by",
        ),
        migrations.RemoveField(
            model_name="labrequest",
            name="specimen_id",
        ),
        migrations.RemoveField(
            model_name="labrequest",
            name="specimen_type",
        ),
        migrations.RemoveField(
            model_name="labresult",
            name="verified_at",
        ),
        migrations.RemoveField(
            model_name="labresult",
            name="verified_by",
        ),
        migrations.AlterField(
            model_name="labrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In-Progress"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
