# Generated by Django 5.2.11 on 2026-02-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_diagnosticreport_result_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticreport',
            name='media_comment',
        ),
        migrations.RemoveField(
            model_name='diagnosticreport',
            name='presented_form_url',
        ),
    ]
