# Generated by Django 5.2.7 on 2026-02-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_remove_diagnosticreport_media_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestdefinition',
            name='normal_range',
            field=models.JSONField(blank=True, default=dict, help_text="JSON structure for ranges, e.g. {'male': '13.5-17.5', 'female': '12.0-15.5'}"),
        ),
        migrations.AddField(
            model_name='labtestdefinition',
            name='unit',
            field=models.CharField(blank=True, help_text='Measurement unit (e.g. mg/dL)', max_length=50, null=True),
        ),
    ]
