# Generated by Django 5.2.7 on 2026-02-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_labtestdefinition_normal_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticreport',
            name='billing_reference',
            field=models.CharField(blank=True, help_text='Reference to the Claim/Invoice generated', max_length=100, null=True),
        ),
    ]
