# Generated by Django 6.0.1 on 2026-01-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("sub_type", models.CharField(blank=True, max_length=100, null=True)),
                ("use", models.CharField(blank=True, max_length=100, null=True)),
                ("billable_period_start", models.DateField(blank=True, null=True)),
                ("billable_period_end", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("priority", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "funds_reserve",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("related_id", models.IntegerField(blank=True, null=True)),
                ("prescription_id", models.IntegerField(blank=True, null=True)),
                (
                    "original_prescription_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("payee_type", models.CharField(blank=True, max_length=100, null=True)),
                ("payee_party_id", models.IntegerField(blank=True, null=True)),
                ("referral_id", models.IntegerField(blank=True, null=True)),
                ("care_team_id", models.IntegerField(blank=True, null=True)),
                ("supporting_info_id", models.IntegerField(blank=True, null=True)),
                ("diagnosis_id", models.IntegerField(blank=True, null=True)),
                ("procedure_id", models.IntegerField(blank=True, null=True)),
                ("insurance_id", models.IntegerField(blank=True, null=True)),
                ("accident_date", models.DateField(blank=True, null=True)),
                (
                    "accident_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "accident_location_address_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("item_id", models.IntegerField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "claim",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "cancelled_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("participant_id", models.IntegerField(blank=True, null=True)),
                ("line_item_id", models.IntegerField(blank=True, null=True)),
                (
                    "total_price_component",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_net_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_gross_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("payment_terms", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("invoice_datetime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "invoice",
            },
        ),
        migrations.CreateModel(
            name="PaymentNotice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_notice_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("request_id", models.IntegerField(blank=True, null=True)),
                ("response_id", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payee_id", models.IntegerField(blank=True, null=True)),
                (
                    "amount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "payment_notice",
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_reconciliation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("outcome", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "disposition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_amount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_amount_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "payment_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("detail_id", models.IntegerField(blank=True, null=True)),
                ("form_code", models.CharField(blank=True, max_length=100, null=True)),
                ("process_note_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "payment_reconciliation",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("servicePeriod_start", models.DateField(blank=True, null=True)),
                ("servicePeriod_end", models.DateField(blank=True, null=True)),
                ("coverage_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("guarantor_id", models.IntegerField(blank=True, null=True)),
                ("part_of_id", models.IntegerField(blank=True, null=True)),
                (
                    "owner_organization",
                    models.ForeignKey(
                        blank=True,
                        db_column="owner_organization_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "account",
            },
        ),
    ]
