# Generated by Django 6.0 on 2026-01-04 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("hospital_id", models.CharField(max_length=50)),
                ("admission_date", models.DateField()),
                ("discharge_date", models.DateField()),
                ("room_ward", models.CharField(max_length=100)),
                ("room_type", models.CharField(max_length=50)),
                ("number_of_days", models.IntegerField(default=0)),
                (
                    "rate_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "attending_physician_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "specialist_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "surgeon_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_professional_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("diet_type", models.CharField(blank=True, max_length=100)),
                ("meals_per_day", models.IntegerField(default=0)),
                ("diet_duration", models.IntegerField(default=0)),
                (
                    "cost_per_meal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "supplies_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "procedure_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "nursing_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "miscellaneous_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "philhealth_coverage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_senior", models.BooleanField(default=False)),
                ("is_pwd", models.BooleanField(default=False)),
                ("is_philhealth_member", models.BooleanField(default=False)),
                ("is_finalized", models.BooleanField(default=False)),
                ("finalized_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="admissions.admission",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "billing_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostics",
                        to="billing.billingrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dosage", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "billing_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="billing.billingrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Credit Card", "Credit Card"),
                            ("Debit Card", "Debit Card"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Check", "Check"),
                            ("PhilHealth", "PhilHealth"),
                            ("HMO", "HMO"),
                        ],
                        max_length=50,
                    ),
                ),
                ("or_number", models.CharField(max_length=50, unique=True)),
                ("cashier", models.CharField(max_length=100)),
                ("payment_date", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "billing_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.billingrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
