# Generated by Django 6.0.2 on 2026-02-18 22:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("subject_id", models.BigIntegerField()),
                ("servicePeriod_start", models.DateField(blank=True, null=True)),
                ("servicePeriod_end", models.DateField(blank=True, null=True)),
                (
                    "coverage_reference_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "coverage_priority",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("owner_id", models.BigIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("guarantor_party_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "guarantor_onHold",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("guarantor_period_start", models.DateField(blank=True, null=True)),
                ("guarantor_period_end", models.DateField(blank=True, null=True)),
                ("partOf_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "account",
                "indexes": [
                    models.Index(
                        fields=["subject_id"], name="account_subject_a696dc_idx"
                    ),
                    models.Index(fields=["status"], name="account_status_a9dc5b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("claim_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("subType", models.CharField(blank=True, max_length=100, null=True)),
                ("use", models.CharField(blank=True, max_length=255, null=True)),
                ("subject_id", models.BigIntegerField()),
                ("enterer_id", models.BigIntegerField(blank=True, null=True)),
                ("insurer_id", models.BigIntegerField(blank=True, null=True)),
                ("provider_id", models.BigIntegerField(blank=True, null=True)),
                ("facility_id", models.BigIntegerField(blank=True, null=True)),
                ("prescription_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "originalPrescription_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("referral_id", models.BigIntegerField(blank=True, null=True)),
                ("billablePeriod_start", models.DateField(blank=True, null=True)),
                ("billablePeriod_end", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("priority", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fundsReserve",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("related_claim_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "related_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "related_relationship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payee_type", models.CharField(blank=True, max_length=100, null=True)),
                ("payee_party_id", models.BigIntegerField(blank=True, null=True)),
                ("accident_date", models.DateField(blank=True, null=True)),
                (
                    "accident_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "accident_location_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "accident_location_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "billing_claim",
                "indexes": [
                    models.Index(
                        fields=["subject_id"], name="billing_cla_subject_dc511e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="billing_cla_status_aea0b1_idx"
                    ),
                    models.Index(
                        fields=["created"], name="billing_cla_created_6e42ad_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClaimItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "careTeamSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "diagnosisSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "procedureSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "informationSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("revenue", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "productOrService",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("modifier", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "programCode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "servicedDate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("servicedPeriod_start", models.DateField(blank=True, null=True)),
                ("servicedPeriod_end", models.DateField(blank=True, null=True)),
                (
                    "locationCodeableConcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "locationAddress",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "locationReference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unitPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("factor", models.CharField(blank=True, max_length=255, null=True)),
                ("net", models.CharField(blank=True, max_length=255, null=True)),
                ("bodySite", models.CharField(blank=True, max_length=255, null=True)),
                ("subSite", models.CharField(blank=True, max_length=255, null=True)),
                ("udi", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.claim",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_item",
            },
        ),
        migrations.CreateModel(
            name="ClaimItemDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                ("revenue", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "productOrService",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("modifier", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "programCode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unitPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("factor", models.CharField(blank=True, max_length=255, null=True)),
                ("net", models.CharField(blank=True, max_length=255, null=True)),
                ("udi", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "claim_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="billing.claimitem",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_item_detail",
            },
        ),
        migrations.CreateModel(
            name="ClaimItemDetailSubDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                ("revenue", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "productOrService",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("modifier", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "programCode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unitPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("factor", models.CharField(blank=True, max_length=255, null=True)),
                ("net", models.CharField(blank=True, max_length=255, null=True)),
                ("udi", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_details",
                        to="billing.claimitemdetail",
                    ),
                ),
            ],
            options={
                "db_table": "claim_item_detail_sub_detail",
            },
        ),
        migrations.CreateModel(
            name="ClaimProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "procedureCodeableConcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "procedureReference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("udi", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="billing.claim",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_procedure",
            },
        ),
        migrations.CreateModel(
            name="ClaimResponse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "claimResponse_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("subType", models.CharField(blank=True, max_length=100, null=True)),
                ("use", models.CharField(blank=True, max_length=255, null=True)),
                ("subject_id", models.BigIntegerField()),
                ("insurer_id", models.BigIntegerField(blank=True, null=True)),
                ("requestor_id", models.BigIntegerField(blank=True, null=True)),
                ("request_id", models.BigIntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=255, null=True)),
                ("disposition", models.TextField(blank=True, null=True)),
                ("preAuthRef", models.CharField(blank=True, max_length=255, null=True)),
                ("preAuthPeriod_start", models.DateField(blank=True, null=True)),
                ("preAuthPeriod_end", models.DateField(blank=True, null=True)),
                ("payeeType", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "payment_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_adjustment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_adjustmentReason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "fundsReserve",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("formCode", models.CharField(blank=True, max_length=100, null=True)),
                ("form", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "billing_claim_response",
                "indexes": [
                    models.Index(
                        fields=["subject_id"], name="billing_cla_subject_dd57ce_idx"
                    ),
                    models.Index(
                        fields=["status"], name="billing_cla_status_d9844e_idx"
                    ),
                    models.Index(
                        fields=["request_id"], name="billing_cla_request_e92333_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClaimResponseAddItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itemSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "detailSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subDetailSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("provider", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "productOrService",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("modifier", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "programCode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "servicedDate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("servicedPeriod_start", models.DateField(blank=True, null=True)),
                ("servicedPeriod_end", models.DateField(blank=True, null=True)),
                (
                    "location_codeableConcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unitPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("factor", models.CharField(blank=True, max_length=255, null=True)),
                ("net", models.CharField(blank=True, max_length=255, null=True)),
                ("bodySite", models.CharField(blank=True, max_length=255, null=True)),
                ("subSite", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "detail_productOrService",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "detail_modifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "detail_subDetail_productOrService",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "detail_subDetail_modifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claim_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_items",
                        to="billing.claimresponse",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_response_add_item",
            },
        ),
        migrations.CreateModel(
            name="ClaimResponseError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itemSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "detailSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subDetailSequence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "claim_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="billing.claimresponse",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_response_error",
            },
        ),
        migrations.CreateModel(
            name="ClaimResponseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                ("noteNumbers", models.TextField(blank=True, null=True)),
                (
                    "adjudication_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "adjudication_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "adjudication_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "adjudication_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claim_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.claimresponse",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_response_item",
            },
        ),
        migrations.CreateModel(
            name="ClaimResponseItemDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                ("noteNumbers", models.TextField(blank=True, null=True)),
                (
                    "adjudication_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "adjudication_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "adjudication_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "adjudication_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claim_response_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="billing.claimresponseitem",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_response_item_detail",
            },
        ),
        migrations.CreateModel(
            name="ClaimResponseItemSubDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                ("noteNumbers", models.TextField(blank=True, null=True)),
                (
                    "adjudication_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "adjudication_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "adjudication_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "adjudication_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_details",
                        to="billing.claimresponseitemdetail",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_response_item_sub_detail",
            },
        ),
        migrations.CreateModel(
            name="ClaimResponseProcessNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("language", models.TextField(blank=True, null=True)),
                (
                    "claim_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_notes",
                        to="billing.claimresponse",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_response_process_note",
            },
        ),
        migrations.CreateModel(
            name="ClaimResponseTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "claim_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totals",
                        to="billing.claimresponse",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_response_total",
            },
        ),
        migrations.CreateModel(
            name="ClaimSupportingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("timing_date", models.DateField(blank=True, null=True)),
                ("timing_period_start", models.DateField(blank=True, null=True)),
                ("timing_period_end", models.DateField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "value_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "value_attachment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "value_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_info",
                        to="billing.claim",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_supporting_info",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cancelled_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("subject_id", models.BigIntegerField()),
                ("recipient_id", models.BigIntegerField(blank=True, null=True)),
                ("issuer_id", models.BigIntegerField(blank=True, null=True)),
                ("account_id", models.BigIntegerField(blank=True, null=True)),
                ("participant_actor_id", models.BigIntegerField(blank=True, null=True)),
                ("invoice_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "participant_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "total_net_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_net_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "total_gross_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_gross_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "billing_invoice",
                "indexes": [
                    models.Index(
                        fields=["subject_id"], name="billing_inv_subject_f81a25_idx"
                    ),
                    models.Index(
                        fields=["status"], name="billing_inv_status_541249_idx"
                    ),
                    models.Index(
                        fields=["invoice_datetime"],
                        name="billing_inv_invoice_fb2b7b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "chargeitem_reference_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "chargeitem_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "net_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "gross_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "billing_invoice_line_item",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItemPriceComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "factor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_components",
                        to="billing.invoicelineitem",
                    ),
                ),
            ],
            options={
                "db_table": "billing_invoice_line_item_price_component",
            },
        ),
        migrations.CreateModel(
            name="InvoiceTotalPriceComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "factor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="total_price_components",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "billing_invoice_total_price_component",
            },
        ),
        migrations.CreateModel(
            name="PaymentNotice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "payment_notice_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_datetime", models.DateTimeField(blank=True, null=True)),
                ("request_reference_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "response_reference_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("provider_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "payment_reconciliation_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("payee_id", models.BigIntegerField(blank=True, null=True)),
                ("recipient_id", models.BigIntegerField(blank=True, null=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
            ],
            options={
                "db_table": "billing_payment_notice",
                "indexes": [
                    models.Index(
                        fields=["status"], name="billing_pay_status_1edd30_idx"
                    ),
                    models.Index(
                        fields=["payment_date"], name="billing_pay_payment_5bcec9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("status", models.CharField(db_index=True, max_length=100)),
                (
                    "payment_reconciliation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("created_datetime", models.DateTimeField(blank=True, null=True)),
                ("payment_issuer_id", models.BigIntegerField(blank=True, null=True)),
                ("request_task_id", models.BigIntegerField(blank=True, null=True)),
                ("requestor_id", models.BigIntegerField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=255, null=True)),
                ("disposition", models.TextField(blank=True, null=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_amount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_amount_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "payment_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("form_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "billing_payment_reconciliation",
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "predecessor_identifier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("request_id", models.BigIntegerField(blank=True, null=True)),
                ("submitter_id", models.BigIntegerField(blank=True, null=True)),
                ("response_id", models.BigIntegerField(blank=True, null=True)),
                ("responsible_id", models.BigIntegerField(blank=True, null=True)),
                ("payee_id", models.BigIntegerField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "amount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "payment_reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="billing.paymentreconciliation",
                    ),
                ),
            ],
            options={
                "db_table": "billing_payment_reconciliation_detail",
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliationProcessNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "payment_reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_notes",
                        to="billing.paymentreconciliation",
                    ),
                ),
            ],
            options={
                "db_table": "billing_payment_reconciliation_process_note",
            },
        ),
        migrations.CreateModel(
            name="ClaimCareTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                ("provider_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "responsible",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_team",
                        to="billing.claim",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_care_team",
                "indexes": [
                    models.Index(
                        fields=["claim"], name="billing_cla_claim_i_b8ddbe_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClaimDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "diagnosisCodeableConcept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "diagnosisReference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "onAdmission",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "packageCode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="billing.claim",
                    ),
                ),
            ],
            options={
                "db_table": "billing_claim_diagnosis",
                "indexes": [
                    models.Index(
                        fields=["claim"], name="billing_cla_claim_i_082d32_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="claimitem",
            index=models.Index(fields=["claim"], name="billing_cla_claim_i_137ac4_idx"),
        ),
        migrations.AddIndex(
            model_name="claimitemdetail",
            index=models.Index(
                fields=["claim_item"], name="billing_cla_claim_i_2f0263_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimitemdetailsubdetail",
            index=models.Index(
                fields=["detail"], name="claim_item__detail__2c455c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimprocedure",
            index=models.Index(fields=["claim"], name="billing_cla_claim_i_9a17a4_idx"),
        ),
        migrations.AddIndex(
            model_name="claimresponseadditem",
            index=models.Index(
                fields=["claim_response"], name="billing_cla_claim_r_cd9655_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimresponseerror",
            index=models.Index(
                fields=["claim_response"], name="billing_cla_claim_r_b8d1de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimresponseitem",
            index=models.Index(
                fields=["claim_response"], name="billing_cla_claim_r_b95582_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimresponseitemdetail",
            index=models.Index(
                fields=["claim_response_item"], name="billing_cla_claim_r_26261f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimresponseitemsubdetail",
            index=models.Index(
                fields=["detail"], name="billing_cla_detail__3b4642_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimresponseprocessnote",
            index=models.Index(
                fields=["claim_response"], name="billing_cla_claim_r_919ba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimresponsetotal",
            index=models.Index(
                fields=["claim_response"], name="billing_cla_claim_r_ea8060_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimsupportinginfo",
            index=models.Index(fields=["claim"], name="billing_cla_claim_i_f0e08d_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(
                fields=["invoice"], name="billing_inv_invoice_78dcb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicelineitempricecomponent",
            index=models.Index(
                fields=["line_item"], name="billing_inv_line_it_1c65f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicetotalpricecomponent",
            index=models.Index(
                fields=["invoice"], name="billing_inv_invoice_dcc54e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(fields=["status"], name="billing_pay_status_ebbdbb_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["payment_date"], name="billing_pay_payment_c86248_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationdetail",
            index=models.Index(
                fields=["payment_reconciliation"], name="billing_pay_payment_35fbb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationprocessnote",
            index=models.Index(
                fields=["payment_reconciliation"], name="billing_pay_payment_a584e3_idx"
            ),
        ),
    ]
