# Generated by Django 6.0 on 2026-01-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="or_number",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
