# Generated by Django 5.2.7 on 2026-02-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='reference_type',
            field=models.CharField(blank=True, help_text='lab_request, medication_request', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_gross_currency',
            field=models.CharField(blank=True, default='PHP', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_gross_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_net_currency',
            field=models.CharField(blank=True, default='PHP', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_net_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
