# Generated by Django 5.2.7 on 2026-02-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_invoicelineitem_reference_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
