# Generated by Django 5.2.7 on 2026-02-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoicelineitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreconciliation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice'),
        ),
    ]
