# Generated by Django 6.0.2 on 2026-02-17 08:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_paymentreconciliation_invoice"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="claim",
            name="billing_cla_patient_499c90_idx",
        ),
        migrations.RemoveIndex(
            model_name="claimresponse",
            name="billing_cla_patient_3b4551_idx",
        ),
        migrations.RenameField(
            model_name="claim",
            old_name="patient_id",
            new_name="subject_id",
        ),
        migrations.RenameField(
            model_name="claimresponse",
            old_name="patient_id",
            new_name="subject_id",
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="gross_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="net_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["subject_id"], name="billing_cla_subject_dc511e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimresponse",
            index=models.Index(
                fields=["subject_id"], name="billing_cla_subject_dd57ce_idx"
            ),
        ),
    ]
