from django.db import models
from core.models import TimeStampedModel, FHIRResourceModel

class Medication(FHIRResourceModel):
    medication_id = models.AutoField(primary_key=True)
    code_code = models.CharField(max_length=100, unique=True, null=True, blank=True)
    code_display = models.CharField(max_length=100, null=True, blank=True)
    code_system = models.CharField(max_length=100, null=True, blank=True)
    code_version = models.CharField(max_length=100, null=True, blank=True)
    implicit_rules = models.CharField(max_length=255, null=True, blank=True)
    class Meta:
        db_table = 'medication'

class MedicationRequest(FHIRResourceModel):
    medication_request_id = models.AutoField(primary_key=True)
    subject = models.ForeignKey('patients.Patient', on_delete=models.PROTECT, db_column='subject_id')
    encounter = models.ForeignKey('admission.Encounter', on_delete=models.PROTECT, db_column='encounter_id')
    requester = models.ForeignKey('accounts.Practitioner', on_delete=models.PROTECT, db_column='requester_id', null=True, blank=True, related_name='medication_requests_requested')
    performer = models.ForeignKey('accounts.Practitioner', on_delete=models.PROTECT, db_column='performer_id', null=True, blank=True, related_name='medication_requests_performed')
    recorder = models.ForeignKey('accounts.Practitioner', on_delete=models.PROTECT, db_column='recorder_id', null=True, blank=True, related_name='medication_requests_recorded')
    based_on = models.ForeignKey('admission.ServiceRequest', on_delete=models.PROTECT, db_column='based_on_id', null=True, blank=True, related_name='medication_requests')
    insurance = models.ForeignKey('billing.Coverage', on_delete=models.PROTECT, db_column='insurance_id', null=True, blank=True, related_name='medication_requests')
    reported_reference = models.ForeignKey('accounts.Practitioner', on_delete=models.PROTECT, db_column='reported_reference_id', null=True, blank=True, related_name='reported_medication_requests')
    reason_reference = models.ForeignKey('patients.Condition', on_delete=models.PROTECT, db_column='reason_reference_id', null=True, blank=True, related_name='reason_medication_requests')
    medication_reference = models.CharField(max_length=255, null=True, blank=True)
    medication_code = models.CharField(max_length=100, null=True, blank=True)
    medication_display = models.CharField(max_length=100, null=True, blank=True)
    medication_system = models.CharField(max_length=100, null=True, blank=True)
    intent = models.CharField(max_length=255, null=True, blank=True)
    category = models.CharField(max_length=255, null=True, blank=True)
    priority = models.CharField(max_length=255, null=True, blank=True)
    do_not_perform = models.BooleanField(null=True, blank=True)
    reported_boolean = models.BooleanField(null=True, blank=True)
    authored_on = models.DateTimeField(null=True, blank=True)
    status_reason = models.CharField(max_length=100, null=True, blank=True)
    reason_code = models.CharField(max_length=100, null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    dosage_text = models.TextField(null=True, blank=True)
    dosage_site = models.CharField(max_length=255, null=True, blank=True)
    dosage_route = models.CharField(max_length=255, null=True, blank=True)
    dosage_method = models.CharField(max_length=255, null=True, blank=True)
    dosage_dose_value = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    dosage_dose_unit = models.CharField(max_length=255, null=True, blank=True)
    dosage_rate_quantity_value = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    dosage_rate_quantity_unit = models.CharField(max_length=50, null=True, blank=True)
    dosage_rate_ratio_numerator = models.CharField(max_length=255, null=True, blank=True)
    dosage_rate_ratio_denominator = models.CharField(max_length=255, null=True, blank=True)
    dispense_quantity = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    dispense_initial_fill_quantity = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    dispense_initial_fill_duration = models.CharField(max_length=255, null=True, blank=True)
    dispense_interval = models.CharField(max_length=255, null=True, blank=True)
    dispense_validity_period_start = models.CharField(max_length=255, null=True, blank=True)
    dispense_validity_period_end = models.CharField(max_length=255, null=True, blank=True)
    dispense_repeats_allowed = models.CharField(max_length=255, null=True, blank=True)
    group_identifier = models.CharField(max_length=100, null=True, blank=True)
    course_of_therapy_type = models.CharField(max_length=100, null=True, blank=True)
    instantiates_canonical = models.CharField(max_length=255, null=True, blank=True)
    instantiates_uri = models.CharField(max_length=255, null=True, blank=True)
    performer_type = models.CharField(max_length=100, null=True, blank=True)
    class Meta:
        db_table = 'medication_request'

class Inventory(TimeStampedModel):
    inventory_id = models.AutoField(primary_key=True)
    item_code = models.CharField(max_length=100, null=True, blank=True)
    item_name = models.CharField(max_length=255, null=True, blank=True)
    category = models.CharField(max_length=255, null=True, blank=True)
    batch_number = models.CharField(max_length=255, null=True, blank=True)
    current_stock = models.IntegerField(null=True, blank=True)
    reorder_level = models.IntegerField(null=True, blank=True)
    unit_of_measure = models.CharField(max_length=255, null=True, blank=True)
    unit_cost = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    status = models.CharField(max_length=100)
    expiry_date = models.DateField(null=True, blank=True)
    last_restocked_datetime = models.DateTimeField(null=True, blank=True)
    created_by = models.CharField(max_length=255, null=True, blank=True)
    class Meta:
        db_table = 'inventory'

class MedicationAdministration(FHIRResourceModel):
    medication_administration_id = models.AutoField(primary_key=True)
    subject = models.ForeignKey('patients.Patient', on_delete=models.PROTECT, db_column='subject_id')
    context = models.ForeignKey('admission.Encounter', on_delete=models.PROTECT, db_column='context_id', null=True, blank=True, related_name='medication_administrations')
    performer_actor = models.ForeignKey('accounts.Practitioner', on_delete=models.PROTECT, db_column='performer_actor_id', null=True, blank=True)
    request = models.ForeignKey('pharmacy.MedicationRequest', on_delete=models.PROTECT, db_column='request_id', null=True, blank=True)
    part_of = models.ForeignKey('admission.Procedure', on_delete=models.PROTECT, db_column='part_of_id', null=True, blank=True, related_name='medication_administrations')
    device = models.ForeignKey('admission.Device', on_delete=models.PROTECT, db_column='device_id', null=True, blank=True, related_name='medication_administrations')
    event_history = models.ForeignKey('monitoring.Observation', on_delete=models.PROTECT, db_column='event_history_id', null=True, blank=True, related_name='event_medication_administrations')
    reason_reference = models.ForeignKey('patients.Condition', on_delete=models.PROTECT, db_column='reason_reference_id', null=True, blank=True, related_name='reason_medication_administrations')
    medication_reference = models.CharField(max_length=255, null=True, blank=True)
    medication_code = models.CharField(max_length=100, null=True, blank=True)
    medication_display = models.CharField(max_length=100, null=True, blank=True)
    medication_system = models.CharField(max_length=100, null=True, blank=True)
    instantiates_uri = models.CharField(max_length=255, null=True, blank=True)
    status_reason = models.CharField(max_length=100, null=True, blank=True)
    category = models.CharField(max_length=255, null=True, blank=True)
    effective_datetime = models.DateTimeField(null=True, blank=True)
    effective_period_start = models.DateField(null=True, blank=True)
    effective_period_end = models.DateField(null=True, blank=True)
    performer_function = models.CharField(max_length=255, null=True, blank=True)
    reason_code = models.CharField(max_length=100, null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    dosage_text = models.TextField(null=True, blank=True)
    dosage_site = models.CharField(max_length=255, null=True, blank=True)
    dosage_route = models.CharField(max_length=255, null=True, blank=True)
    dosage_method = models.CharField(max_length=255, null=True, blank=True)
    dosage_dose_value = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    dosage_dose_unit = models.CharField(max_length=255, null=True, blank=True)
    dosage_rate_quantity_value = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    dosage_rate_quantity_unit = models.CharField(max_length=50, null=True, blank=True)
    dosage_rate_ratio_numerator = models.CharField(max_length=255, null=True, blank=True)
    dosage_rate_ratio_denominator = models.CharField(max_length=255, null=True, blank=True)
    class Meta:
        db_table = 'medication_administration'